### ISSUE TITLE
PyPi build failure

### ISSUE THREAD

**Issue by codeandkey** [EI-CoreBioinformatics/mikado#144]
I'm having issues building this software from PyPi (multiple errors), here is some of the output:

```
Singularity mikado.simg:~> pip3 install mikado
Downloading/unpacking mikado
  Downloading Mikado-1.2.4.tar.gz (19.9MB): 19.9MB downloaded
  Running setup.py (path:/tmp/pip_build_root/mikado/setup.py) egg_info for package mikado
    Compiling Mikado/scales/contrast.pyx because it depends on ./Mikado/utilities/overlap.pxd.
    Cythonizing Mikado/scales/contrast.pyx
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from .resultstorer import ResultStorer
    from ..loci import Transcript
    from ..utilities.overlap cimport c_overlap
    ^
    ------------------------------------------------------------
    
    Mikado/scales/contrast.pyx:3:0: 'utilities.overlap.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from .resultstorer import ResultStorer
    from ..loci import Transcript
    from ..utilities.overlap cimport c_overlap
    ^
    ------------------------------------------------------------
    
    Mikado/scales/contrast.pyx:3:0: 'c_overlap.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from .resultstorer import ResultStorer
    from ..loci import Transcript
    from ..utilities.overlap cimport c_overlap
                                    ^
    ------------------------------------------------------------
    
    Mikado/scales/contrast.pyx:3:33: Name 'c_overlap' not declared in module 'utilities.overlap'
```

there are more errors which I can include if relevant -- hopefully these provide enough information.
Thanks!

**Comment by lucventurini** [comment]
Dear @molecuul ,
                             thank you for reporting the bug. There is something amiss with the PyPI package - it should contain the PXD files that Cython complains are missing.

While I look into the problem, I would recommend the following:

- Download the latest stable release (https://github.com/EI-CoreBioinformatics/mikado/releases/tag/1.2.4)
- Unzip/untar the contents and go inside the folder
- install requirements with pip (`pip install -r requirements.txt`)
- compile the wheel package (`python setup.py bdist_wheel`)
- install the package (`pip install dist/*whl`)

Kind regards

Luca Venturini

**Comment by lucventurini** [comment]
Dear @codeandkey , the next version of Mikado will have this problem solved. I made sure that the necessary files will be packaged, so that compilation and testing will function appropriately.
I will close for now.

**Comment by codeandkey** [comment]
That's great to hear! Thanks much for your hard work.
