### ISSUE TITLE
exon_lines[row.id]["tid"] = row.transcript KeyError: None

### ISSUE THREAD

**Issue by ehsansari123** [EI-CoreBioinformatics/mikado#145]
While running Mikado for a wheat project, I faced an error in prepare stage. Here is the prepare log file:
-------------------------------------------------------------
2019-02-05 16:06:06,913 - prepare - prepare.py:67 - INFO - setup - MainProcess - Command line: /storage/ppl/sarie/miniconda3/bin/mikado prepare --json-conf configuration.yaml
2019-02-05 16:06:07,018 - prepare - prepare.py:435 - ERROR - prepare - MainProcess - None
Traceback (most recent call last):
  File "/storage/ppl/sarie/miniconda3/lib/python3.6/site-packages/Mikado/preparation/prepare.py", line 414, in prepare
    min_length=args.json_conf["prepare"]["minimum_length"])
  File "/storage/ppl/sarie/miniconda3/lib/python3.6/site-packages/Mikado/preparation/prepare.py", line 280, in load_exon_lines
    strand_specific=strand_specific)
  File "/storage/ppl/sarie/miniconda3/lib/python3.6/site-packages/Mikado/preparation/annotation_parser.py", line 448, in load_from_gtf
    exon_lines[row.id]["tid"] = row.transcript
KeyError: None
2019-02-05 16:06:07,019 - prepare - prepare.py:437 - ERROR - prepare - MainProcess - Mikado has encountered an error, exiting
2019-02-05 16:06:07,019 - prepare - prepare.py:447 - INFO - prepare - MainProcess - Finished
----------------------------------------------
I have generated transcripts using class2, trinity and stringtie and other inputs as instructed. speaking with our bioinformatician, we believe some thing is wrong with input file but we could not figure that out. I would be grateful if you could share your thoughts with me.
Thanks 
Ehsan

![class](https://user-images.githubusercontent.com/47370630/52308880-1fe3c500-2964-11e9-8dae-c1e0b163e53b.png)
![junction](https://user-images.githubusercontent.com/47370630/52308881-1fe3c500-2964-11e9-8216-deeb5d38b83c.png)
[list.txt](https://github.com/EI-CoreBioinformatics/mikado/files/2834158/list.txt)
![orfs](https://user-images.githubusercontent.com/47370630/52308882-207c5b80-2964-11e9-9a3b-63e3fe6269f6.png)
[prepare.log](https://github.com/EI-CoreBioinformatics/mikado/files/2834159/prepare.log)
![reference fasta](https://user-images.githubusercontent.com/47370630/52308883-207c5b80-2964-11e9-9100-eac01c74f097.png)
![stringtie screenshot](https://user-images.githubusercontent.com/47370630/52308884-207c5b80-2964-11e9-8511-6c37fc90970e.png)
![trinity](https://user-images.githubusercontent.com/47370630/52308886-207c5b80-2964-11e9-8d8d-eaab39e44bf9.png)

**Comment by lucventurini** [comment]
Dear @ehsansari123,
                                    would you be able to send over the GTF as a text file, or at least the parts that are present on the screenshots? It would make debugging easier. It is most likely a problem of malformed input, but it is hard to find out where from the screenshots.

Kind regards

Luca Venturini

**Comment by ehsansari123** [comment]
Hi Luca,
Many thanks for taking the time to help me out. I notice that the main issue is with the output I get from mapping Trinity transcripts to genome using GMAP. I have build the GMAP database using:
$ gmap_build -D . -T . -d wheatAB -k 13 genome.fasta
and then mapped the transcript to database to get the gff3 output using:
$ gmapl -D . -d wheatAB -B 5 -t 16 -f gff3_gene -x 50 -n 0 ./path/to/Trinity_transcripts.fasta > Trinity_XX.gff3
and I got an output that is different from that provided as sample data in https://github.com/lucventurini/mikado/blob/master/sample_data/trinity.gff3:
the format in sample data is :
---------------------------------------------
##gff-version	3
Chr5	tair10	gene	26578496	26579563	.	-	.	ID=c73_g1_i1.path1.160
Chr5	tair10	transcript	26578496	26579563	95	-	.	ID=c73_g1_i1.mrna1.160;Parent=c73_g1_i1.path1.160;Name=c73_g1_i1.mrna1.160;gene_name=c73_g1_i1
Chr5	tair10	exon	26578496	26578518	.	-	.	ID=c73_g1_i1.mrna1.160.exon1;Parent=c73_g1_i1.mrna1.160
Chr5	tair10	exon	26579301	26579563	.	-	.	ID=c73_g1_i1.mrna1.160.exon2;Parent=c73_g1_i1.mrna1.160
###
Chr5	tair10	gene	26581225	26583874	.	-	.	ID=c11_g1_i2.path1.111
Chr5	tair10	transcript	26581225	26583874	99	-	.	ID=c11_g1_i2.mrna1.111;Parent=c11_g1_i2.path1.111;Name=c11_g1_i2.mrna1.111;gene_name=c11_g1_i2
Chr5	tair10	exon	26581225	26581528	.	-	.	ID=c11_g1_i2.mrna1.111.exon1;Parent=c11_g1_i2.mrna1.111
Chr5	tair10	exon	26583335	26583874	.	-	.	ID=c11_g1_i2.mrna1.111.exon2;Parent=c11_g1_i2.mrna1.111
###
Chr5	tair10	gene	26583216	26583874	.	-	.	ID=c11_g1_i1.path1.350
Chr5	tair10	transcript	26583216	26583874	99	-	.	ID=c11_g1_i1.mrna1.350;Parent=c11_g1_i1.path1.350;Name=c11_g1_i1.mrna1.350;gene_name=c11_g1_i1
Chr5	tair10	exon	26583216	26583874	.	-	.	ID=c11_g1_i1.mrna1.350.exon1;Parent=c11_g1_i1.mrna1.350
-------------------------------------------------------
and what I got is:
-----------------------------------------------
##gff-version   3
# Generated by GMAP version 2018-07-04 using call:  gmapl.sse42 -D . -d wheatAB -B 5 -t 16 -f gff3_gene -x 50 -n 0 ./C679/trinity_out_dir/Trinity-GG.fasta
chr2A_part1	wheatAB	gene	58825699	58826035	.	-	.	ID=TRINITY_GG_7_c0_g1_i1.path1;Name=TRINITY_GG_7_c0_g1_i1
chr2A_part1	wheatAB	mRNA	58825699	58826035	.	-	.	ID=TRINITY_GG_7_c0_g1_i1.mrna1;Name=TRINITY_GG_7_c0_g1_i1;Parent=TRINITY_GG_7_c0_g1_i1.path1;coverage=100.0;identity=99.4;matches=335;mismatches=2;indels=0;unknowns=0
chr2A_part1	wheatAB	exon	58825699	58826035	99	-	.	ID=TRINITY_GG_7_c0_g1_i1.mrna1.exon1;Name=TRINITY_GG_7_c0_g1_i1;Parent=TRINITY_GG_7_c0_g1_i1.mrna1;Target=TRINITY_GG_7_c0_g1_i1 337 1 .
chr2A_part1	wheatAB	CDS	58825758	58826033	99	-	0	ID=TRINITY_GG_7_c0_g1_i1.mrna1.cds1;Name=TRINITY_GG_7_c0_g1_i1;Parent=TRINITY_GG_7_c0_g1_i1.mrna1;Target=TRINITY_GG_7_c0_g1_i1 278 3 .
###
chr2A_part1	wheatAB	gene	59737856	59743049	.	+	.	ID=TRINITY_GG_12_c0_g1_i3.path1;Name=TRINITY_GG_12_c0_g1_i3
chr2A_part1	wheatAB	mRNA	59737856	59743049	.	+	.	ID=TRINITY_GG_12_c0_g1_i3.mrna1;Name=TRINITY_GG_12_c0_g1_i3;Parent=TRINITY_GG_12_c0_g1_i3.path1;coverage=99.3;identity=99.8;matches=868;mismatches=2;indels=0;unknowns=0
chr2A_part1	wheatAB	exon	59737856	59737964	100	+	.	ID=TRINITY_GG_12_c0_g1_i3.mrna1.exon1;Name=TRINITY_GG_12_c0_g1_i3;Parent=TRINITY_GG_12_c0_g1_i3.mrna1;Target=TRINITY_GG_12_c0_g1_i3 767 875 -
chr2A_part1	wheatAB	exon	59738054	59738143	100	+	.	ID=TRINITY_GG_12_c0_g1_i3.mrna1.exon2;Name=TRINITY_GG_12_c0_g1_i3;Parent=TRINITY_GG_12_c0_g1_i3.mrna1;Target=TRINITY_GG_12_c0_g1_i3 677 766 -
chr2A_part1	wheatAB	exon	59738280	59738353	100	+	.	ID=TRINITY_GG_12_c0_g1_i3.mrna1.exon3;Name=TRINITY_GG_12_c0_g1_i3;Parent=TRINITY_GG_12_c0_g1_i3.mrna1;Target=TRINITY_GG_12_c0_g1_i3 603 676 -
chr2A_part1	wheatAB	exon	59740010	59740080	100	+	.	ID=TRINITY_GG_12_c0_g1_i3.mrna1.exon4;Name=TRINITY_GG_12_c0_g1_i3;Parent=TRINITY_GG_12_c0_g1_i3.mrna1;Target=TRINITY_GG_12_c0_g1_i3 532 602 -
chr2A_part1	wheatAB	exon	59742524	59743049	99	+	.	ID=TRINITY_GG_12_c0_g1_i3.mrna1.exon5;Name=TRINITY_GG_12_c0_g1_i3;Parent=TRINITY_GG_12_c0_g1_i3.mrna1;Target=TRINITY_GG_12_c0_g1_i3 6 531 -
chr2A_part1	wheatAB	CDS	59737856	59737964	100	+	0	ID=TRINITY_GG_12_c0_g1_i3.mrna1.cds1;Name=TRINITY_GG_12_c0_g1_i3;Parent=TRINITY_GG_12_c0_g1_i3.mrna1;Target=TRINITY_GG_12_c0_g1_i3 767 875 .
chr2A_part1	wheatAB	CDS	59738054	59738143	100	+	1	ID=TRINITY_GG_12_c0_g1_i3.mrna1.cds2;Name=TRINITY_GG_12_c0_g1_i3;Parent=TRINITY_GG_12_c0_g1_i3.mrna1;Target=TRINITY_GG_12_c0_g1_i3 677 766 .
chr2A_part1	wheatAB	CDS	59738280	59738353	100	+	1	ID=TRINITY_GG_12_c0_g1_i3.mrna1.cds3;Name=TRINITY_GG_12_c0_g1_i3;Parent=TRINITY_GG_12_c0_g1_i3.mrna1;Target=TRINITY_GG_12_c0_g1_i3 603 676 .
chr2A_part1	wheatAB	CDS	59740010	59740054	100	+	0	ID=TRINITY_GG_12_c0_g1_i3.mrna1.cds4;Name=TRINITY_GG_12_c0_g1_i3;Parent=TRINITY_GG_12_c0_g1_i3.mrna1;Target=TRINITY_GG_12_c0_g1_i3 558 602 .
###
chr2A_part1	wheatAB	gene	59737856	59740412	.	+	.	ID=TRINITY_GG_12_c0_g1_i1.path1;Name=TRINITY_GG_12_c0_g1_i1
chr2A_part1	wheatAB	mRNA	59737856	59740412	.	+	.	ID=TRINITY_GG_12_c0_g1_i1.mrna1;Name=TRINITY_GG_12_c0_g1_i1;Parent=TRINITY_GG_12_c0_g1_i1.path1;coverage=99.9;identity=100.0;matches=676;mismatches=0;indels=0;unknowns=0
chr2A_part1	wheatAB	exon	59737856	59737964	100	+	.	ID=TRINITY_GG_12_c0_g1_i1.mrna1.exon1;Name=TRINITY_GG_12_c0_g1_i1;Parent=TRINITY_GG_12_c0_g1_i1.mrna1;Target=TRINITY_GG_12_c0_g1_i1 568 676 -
chr2A_part1	wheatAB	exon	59738054	59738143	100	+	.	ID=TRINITY_GG_12_c0_g1_i1.mrna1.exon2;Name=TRINITY_GG_12_c0_g1_i1;Parent=TRINITY_GG_12_c0_g1_i1.mrna1;Target=TRINITY_GG_12_c0_g1_i1 478 567 -
chr2A_part1	wheatAB	exon	59738280	59738353	100	+	.	ID=TRINITY_GG_12_c0_g1_i1.mrna1.exon3;Name=TRINITY_GG_12_c0_g1_i1;Parent=TRINITY_GG_12_c0_g1_i1.mrna1;Target=TRINITY_GG_12_c0_g1_i1 404 477 -
chr2A_part1	wheatAB	exon	59740010	59740412	100	+	.	ID=TRINITY_GG_12_c0_g1_i1.mrna1.exon4;Name=TRINITY_GG_12_c0_g1_i1;Parent=TRINITY_GG_12_c0_g1_i1.mrna1;Target=TRINITY_GG_12_c0_g1_i1 1 403 -
chr2A_part1	wheatAB	CDS	59737856	59737964	100	+	0	ID=TRINITY_GG_12_c0_g1_i1.mrna1.cds1;Name=TRINITY_GG_12_c0_g1_i1;Parent=TRINITY_GG_12_c0_g1_i1.mrna1;Target=TRINITY_GG_12_c0_g1_i1 568 676 .
chr2A_part1	wheatAB	CDS	59738054	59738143	100	+	1	ID=TRINITY_GG_12_c0_g1_i1.mrna1.cds2;Name=TRINITY_GG_12_c0_g1_i1;Parent=TRINITY_GG_12_c0_g1_i1.mrna1;Target=TRINITY_GG_12_c0_g1_i1 478 567 .
chr2A_part1	wheatAB	CDS	59738280	59738353	100	+	1	ID=TRINITY_GG_12_c0_g1_i1.mrna1.cds3;Name=TRINITY_GG_12_c0_g1_i1;Parent=TRINITY_GG_12_c0_g1_i1.mrna1;Target=TRINITY_GG_12_c0_g1_i1 404 477 .
chr2A_part1	wheatAB	CDS	59740010	59740054	100	+	0	ID=TRINITY_GG_12_c0_g1_i1.mrna1.cds4;Name=TRINITY_GG_12_c0_g1_i1;Parent=TRINITY_GG_12_c0_g1_i1.mrna1;Target=TRINITY_GG_12_c0_g1_i1 359 403 .
###
-------------------------------------------------------------------------------------
It seems that I have different features in the GFF3 files. I really appreciate if you could let me how I should map Trinity transcripts to genome using GMAP. I am sure it is the case since once I omitted the trinity file from input, Mikado worked without errors.
Thanks again for agreeing to help.
Regards
Ehsan

**Comment by ehsansari123** [comment]
Hi Luca,
The run goes on OK in prepare stage with several errors in prepare logs. Just thought It could help you figure out the issue.
Thanks
Ehsan
-----------------------
2019-02-12 13:39:57,275 - prepare - prepare.py:67 - INFO - setup - MainProcess - Command line: /storage/ppl/sarie/miniconda3/envs/MIKADO/bin/mikado prepare --json-conf configuration.yaml
2019-02-12 13:41:20,255 - Checker-4 - finalizing.py:531 - WARNING - __check_phase_correctness - Checker-4 - Stripping the CDS from tr_TRINITY_GG_38456_c1_g1_i2.mrna1, error: "Both UTR presents with a truncated ORF in tr_TRINITY_GG_38456_c1_g1_i2.mrna1
5'UTR: [('UTR', (25592, 25593))]
3' UTR: [('UTR', (24960, 25544))]
2019-02-12 13:41:20,595 - Checker-6 - finalizing.py:531 - WARNING - __check_phase_correctness - Checker-6 - Stripping the CDS from tr_TRINITY_GG_127205_c0_g1_i1.mrna1, error: "Both UTR presents with a truncated ORF in tr_TRINITY_GG_127205_c0_g1_i1.mrna1
5'UTR: [('UTR', (63700, 64050))]
3' UTR: [('UTR', (63533, 63599))]
2019-02-12 13:41:20,656 - Checker-2 - finalizing.py:531 - WARNING - __check_phase_correctness - Checker-2 - Stripping the CDS from tr_TRINITY_GG_45277_c0_g1_i1.mrna1, error: "Both UTR presents with a truncated ORF in tr_TRINITY_GG_45277_c0_g1_i1.mrna1
5'UTR: [('UTR', (63843, 63844))]
3' UTR: [('UTR', (63904, 64156))]
2019-02-12 13:41:20,737 - Checker-5 - finalizing.py:531 - WARNING - __check_phase_correctness - Checker-5 - Stripping the CDS from tr_TRINITY_GG_125141_c0_g1_i1.mrna1, error: "Both UTR presents with a truncated ORF in tr_TRINITY_GG_125141_c0_g1_i1.mrna1
5'UTR: [('UTR', (64733, 64766))]
3' UTR: [('UTR', (64443, 64650))]
2019-02-12 13:41:20,923 - Checker-6 - finalizing.py:531 - WARNING - __check_phase_correctness - Checker-6 - Stripping the CDS from tr_TRINITY_GG_126363_c0_g1_i1.mrna1, error: "Both UTR presents with a truncated ORF in tr_TRINITY_GG_126363_c0_g1_i1.mrna1
5'UTR: [('UTR', (87350, 87350))]
3' UTR: [('UTR', (87136, 87263))]
2019-02-12 13:41:21,488 - Checker-3 - finalizing.py:531 - WARNING - __check_phase_correctness - Checker-3 - Stripping the CDS from tr_TRINITY_GG_26242_c0_g1_i1.mrna1, error: "Both UTR presents with a truncated ORF in tr_TRINITY_GG_26242_c0_g1_i1.mrna1
5'UTR: [('UTR', (395501, 395502))]
3' UTR: [('UTR', (395558, 395723))]
2019-02-12 13:41:21,560 - Checker-4 - finalizing.py:531 - WARNING - __check_phase_correctness - Checker-4 - Stripping the CDS from tr_TRINITY_GG_155697_c0_g1_i1.mrna1, error: "Both UTR presents with a truncated ORF in tr_TRINITY_GG_155697_c0_g1_i1.mrna1
5'UTR: [('UTR', (697575, 697576))]
3' UTR: [('UTR', (697935, 698024))]
2019-02-12 13:41:21,585 - Checker-5 - finalizing.py:531 - WARNING - __check_phase_correctness - Checker-5 - Stripping the CDS from tr_TRINITY_GG_26248_c0_g1_i1.mrna1, error: "Both UTR presents with a truncated ORF in tr_TRINITY_GG_26248_c0_g1_i1.mrna1
5'UTR: [('UTR', (1157797, 1157798))]
3' UTR: [('UTR', (1158350, 1158525))]
2019-02-12 13:41:21,749 - Checker-10 - finalizing.py:531 - WARNING - __check_phase_correctness - Checker-10 - Stripping the CDS from tr_TRINITY_GG_31333_c0_g1_i1.mrna1, error: "Both UTR presents with a truncated ORF in tr_TRINITY_GG_31333_c0_g1_i1.mrna1
5'UTR: [('UTR', (1209774, 1209775))]
3' UTR: [('UTR', (1209822, 1210177))]
2019-02-12 13:41:21,953 - Checker-6 - finalizing.py:531 - WARNING - __check_phase_correctness - Checker-6 - Stripping the CDS from tr_TRINITY_GG_28076_c0_g1_i1.mrna1, error: "Both UTR presents with a truncated ORF in tr_TRINITY_GG_28076_c0_g1_i1.mrna1
5'UTR: [('UTR', (1846517, 1846517))]

**Comment by lucventurini** [comment]
Dear @ehsansari123,
                                      using format 3 (gff3_match_cdna) should return a Trinity alignment which will be parsed correctly by Mikado.

Alternatively, you can have Mikado stripping the CDS automatically from Trinity transcripts (which I would recommend to do anyhow), just add "--strip-cds" to the command line.

I hope this helps.

Kind regards

**Comment by ehsansari123** [comment]
Hi Luca,
I changed the format and it worked. Thanks a lot for your kind supports.
Cheers!
Ehsan

**Comment by lucventurini** [comment]
Dear @ehsansari123 ,
                                      not a problem, it has been a pleasure!
I will close the issue as it is now resolved.
