### ISSUE TITLE
Daijin bugs

### ISSUE THREAD

**Issue by tommathers** [EI-CoreBioinformatics/mikado#146]
Hi,

Just noticed a couple of bugs when experimenting running mikado via daijin. I am running v1.3devel installed at EI.  

When giving long read data in addition to RNAseq, daijin configure does not add a long read mapping option to the configuration file by default and I can't find a flag to add it (maybe hidden option?). This means that daijin assemble ignores the the long read data. I fixed this by adding gmap to the configuration file after running configure:

`long_read_align_methods:
  gmap:
  - ''`

Daijin also seems to be very sensitive to the version of gmap being used. I tested with gmap-20180704 and it fails in the index step (gmap_build) even though this actually runs correctly. I think it is looking for an index file that is not generated by the newer version of gmap:

`MissingOutputException in line 690 of /ei/software/testing/mikado/1.3devel/x86_64/lib/python3.6/site-packages/Mikado/daijin/tr.snakefile:
Missing files after 1 seconds:
Daijin/2-alignments/gmap/index/Daijin/Daijin.sachildguide1024
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
`

Tested with gmap-20170620 and got a similar error looking for the same sachildguide1024 file:

`Error in rule gmap_index:
    jobid: 18
    output: Daijin/2-alignments/gmap/index/Daijin/Daijin.sachildguide1024
    log: Daijin/2-alignments/gmap.index.log

RuleException:
CalledProcessError in line 697 of /ei/software/testing/mikado/1.3devel/x86_64/lib/python3.6/site-packages/Mikado/daijin/tr.snakefile:
Command ' set -euo pipefail;   gmap_build --dir=Daijin/2-alignments/gmap/index --db=Daijin ../../../Frozen_v2/Myzus_persicae_O.v2.0.scaffolds.fa > Daijin/2-alignments/gmap.index.log 2>&1 ' returned non-zero exit status 255.
  File "/ei/software/testing/mikado/1.3devel/x86_64/lib/python3.6/site-packages/Mikado/daijin/tr.snakefile", line 697, in __rule_gmap_index
  File "/tgac/software/testing/python_anaconda/5.2.0_py3.6_cs/x86_64/lib/python3.6/concurrent/futures/thread.py", line 56, in run
`
Fixed by going back to gmap-20150929 (2015 version). With this version all steps run correctly. 

Tom.

**Comment by tommathers** [comment]
Some of the code got a bit mixed up. 

Line added to the config file for the long read mapping was:

long_read_align_methods:
 gmap:
  - ''

**Comment by lucventurini** [comment]
Hi @tommathers ,
                              thank you for reporting this. We actually stopped developing Daijin at the moment as we are devoting energies for a new pipeline (https://github.com/EI-CoreBioinformatics/ei-annotation).
I will noentheless have a look at what you reported and try to fix it before the next release of Mikado.

**Comment by lucventurini** [comment]
Hi @tommathers ,
                               the latest commit should fix the issue. I will close it, with the caveat that any further development will happen in [ei-annotation](https://github.com/lucventurini/ei-annotation); Daijin will remain for legacy purposes only.
As an example, ei-annotation already supports minimap2 for long read alignment, while Daijin does not and there is no plan to expand its capability in that sense.

Best

Luca
