### ISSUE TITLE
Installation troubles -- EI internal issue

### ISSUE THREAD

**Issue by cschu** [EI-CoreBioinformatics/mikado#149]
Just making a note of this here:

Following the installation procedures as given in the README (python setup.py test, python setup.py bdist_wheel, pip3 install dist/*whl [with --prefix option]) appears to result in numpy and sortedcontainers missing from the base python (python_anaconda-5.2.0_py3.6_cs), which in turn causes versions 1.3devel and 1.2.4 to fail (but not the latest version as cloned from github).

Fixed this by pip install numpy and pip install sortedcontainers, but this is quite annoying behaviour that the base python is modified. If possible, any EI-internal installations should be in containers.

**Comment by lucventurini** [comment]
Hi Christian,
                    performing the installation with

$ pip install --prefix=$PREFIX -U --upgrade-strategy="only-if-needed" 

*could* solve the problem.

Best

**Comment by lucventurini** [comment]
Confirmed the fix. I installed "git_20190215" with the above command, and numpy was **not** removed from the general directory.

**Comment by cschu** [comment]
Thanks, Luca, will do that in the future. I still think we should consider containering installations at some point.

**Comment by lucventurini** [comment]
Hi @cschu , I am writing up a Singularity recipe for installing Mikado. It should be in the master trunk within the morning.

I would advise to use it for production releases only though, as I am modifying the current "git" installations on the fly to triage and solve small bugs that are cropping up while adding features.

Best
