### ISSUE TITLE
Fix Loader-less yaml.load() calls

### ISSUE THREAD

**Issue by cschu** [EI-CoreBioinformatics/mikado#156]
/usr/local/conda/lib/python3.6/site-packages/Mikado/configuration/configurator.py:505: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  scoring = yaml.load(scoring_file)

**Comment by lucventurini** [comment]
OK, I will fix it for 1.5!
