### ISSUE TITLE
Wrong attributes after converting from BAM

### ISSUE THREAD

**Issue by Tierhon** [EI-CoreBioinformatics/mikado#157]
Dear Luca,
I have mapped some IsoSeq3 transcripts with minimap 2, and have converted the BAM file to GTF with this script:
https://github.com/EI-CoreBioinformatics/mikado/blob/master/util/bam2gtf.py

When running mikado prepare, I get a lot of these errors:
`Wrong attributes (['"']) in line:
LG01    bam2gtf transcript      673836  675790  60      -       .       gene_id "transcript/26892.gene"; transcript_id "transcript/26892"; identity "NA"; coverage "90.56"; cigar "2S100M2D202M1I333M13I512M6D1M1D444N354M156S"; NM "31"; ms "1445"; AS "1409"; nn "0"; ts "-"; tp "P"; cm "444"; s1 "1428"; s2 "1162"; de "0.00860000029206276"; SA "GmG20150304_scaffold_6248,682,-,1516S157M1576D1S,0,4;";
`
Can you understand what is happening? Are these transcripts lost?

Thank you. 

Ole

**Comment by lucventurini** [comment]
Dear @Tierhon,
                             Thank you for reporting this issue. I think I might have fixed it already today, as I was working specifically on this part of the code (see e41122d8). We might be able to verify the fix in two ways:
- if the data is not confidential, you could send me a small subsection of the Bam, so that I can check directly
- alternatively, you could install the software directly from the github repo and check whether the changes from today solve your issue.

Hope this helps.

Kind regards

Luca Venturini

**Comment by Tierhon** [comment]
Dear Luca.

I am feeling really stupid right now. I cloned the git repository, and installed it by 
`python3 setup.py test;
python3 setup.py bdist_wheel;
pip install dist/*whl`

This was done with in a miniconda3 environment. But, where is the binary? The mikado file that drives the procedures. I can't find it anywhere, and there does not seem to be any apparent issues in the installation.

Ole

**Comment by lucventurini** [comment]
Hi Tierhon,
                    the binary should have been installed in your PATH - ie inside the Miniconda3 folder.
You should be able to test this by doing:
```
$ python3
[1] import Mikado
[2] print(Mikado.__version__)
1.5
```

Best
Luca

**Comment by Tierhon** [comment]
Hmm, something went wrong somewhere. I am sorry. I get this result: 
`Python 3.6.7 | packaged by conda-forge | (default, Feb 20 2019, 02:51:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Mikado
>>> print(Mikado.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'Mikado' has no attribute '__version__'`

I can send you the `python setup.py test` result on email. Not sure how to troubleshoot this.

Ole

**Comment by lucventurini** [comment]
From the mail thread: the problem is that there are some attributes in the GTF which contain, **wrongly**, the character ";" within. This confuses the parser and causes the problem.
To be fixed ASAP.

**Comment by Tierhon** [comment]
Great! Thank you.

**Comment by lucventurini** [comment]
Dear @Tierhon , the problem should now be fixed. Please let me know!

**Comment by Tierhon** [comment]
I had no issues loading these files now. Thank you!

**Comment by lucventurini** [comment]
Excellent! And thanks to this issue, I should also have fixed the problems with `python setup.py test`. So double progress :-)
