### ISSUE TITLE
Remove unused parameters from the configuration file

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/mikado#158]
Currently the configuration file has a little bit of legacy flags. 
One such flags, for example, is "strand_specific" under the "prepare" section.
Ideally, we should clean up the file to make sure that such legacy parts do not engender confusion in the user.

**Comment by lucventurini** [comment]
Hi @swarbred , @gemygk , 
                                             the configuration file should now be simplified.
If you could have a look at how it looks like to you, I could get this issue closed.

**Comment by swarbred** [comment]
Seems ok, we will need to likely change the following 

    ts_distance: 300
    ts_max_splices: 1

to perhaps

    ts_distance: 1000
    ts_max_splices: 2

but can be confirmed once we have the padding finalised

I believe the values below are not used by Mikado but rather by Daijin, can we add a comment to indicate how they are used.

reference:
  genome: genome.fa
  max_intron: 4500000
  min_intron: 20

**Comment by lucventurini** [comment]
Hi @swarbred ,
                          I changed the default values to:
```
ts_distance: 1000
ts_max_splices: 2
```

for the time being. Regarding this:

```yaml
reference:
  genome: genome.fa
  max_intron: 4500000
  min_intron: 20
```

"genome" is used by Mikado itself.
"max_intron" and "min_intron" are **not** present in the Mikado configuration file now. I suspect they are present in the ones of GMC because they are in the `external.yaml` file provided by @cschu . @cschu , could you confirm that you created external.yaml with an older version of Mikado? This would explain the presence of the values.

**Comment by cschu** [comment]
Yes, the external.yaml to drive GMC was made a long time ago. Must have taken it from the Melia Azaderach or Quillaja saponaria annotation (just like any other input for the GMC tests).

**Comment by lucventurini** [comment]
Great. As this is the case, I will close the issue.
