### ISSUE TITLE
Require SQLAlchemy 1.3

### ISSUE THREAD

**Issue by Tierhon** [EI-CoreBioinformatics/mikado#162]
Hi again,
if I read this correctly you are using a function (here at least: https://github.com/EI-CoreBioinformatics/mikado/blob/2951e46d02bf3c62b9d673399d0bf674179bc605/Mikado/loci/superlocus.py#L662) which is new in SQLAlchemy 1.3: https://docs.sqlalchemy.org/en/latest/orm/session_api.html#sqlalchemy.orm.session.close_all_sessions. 

I guess you can change requirements to 1.3 instead of 1 as it is now (https://github.com/EI-CoreBioinformatics/mikado/blob/2951e46d02bf3c62b9d673399d0bf674179bc605/requirements.txt#L7).

Ole

**Comment by lucventurini** [comment]
Done, thanks!
