### ISSUE TITLE
Improvements to Mikado compare

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/mikado#166]
Mikado compare has been going under a number of revisions for 1.5. Specifically:
- added multiprocessing
- added the ability of analysing BAM predictions (for e.g. Nanopore alignments)
- Internally, the cython routine now compares C-level interval trees rather than Python-level sets - increasing speed and allowing for more refined matching. Specifically:
  - added the possibility of specifying a "fuzzy match" for introns - basically, considering an intron as a match if the boundaries are within a certain distance.
- In the final statistics, Mikado compare now reports both **redundant** and **non-redundant** intron chain statistics
  
However, the improvements are not finished yet. Specifically:
- multiprocessing has increased the memory usage, most probably because data is held in memory before being returned to the main process. This has to be fixed before release
- The "fuzzy matching" only functions **at the level of the single match**, but not at the level of the final statistics. This might engender confusion.
- As we added redundant intron-chain statistics, so we should do as well for the intron level
- We should add splice-level statistics as well.

**Comment by swarbred** [comment]
@lucventurini looks like you added the redundant / non-redundant option for introns, I see you made some additional changes yesterday. Is this in a state we should test/use or should we hold off for now i.e. if you were planning to make further changes shortly.

**Comment by lucventurini** [comment]
I am still making changes, please hold off for now. I need to verify that the multiprocessing is implemented correctly.

I will let you know when it's ready to be trialled!

**Comment by lucventurini** [comment]
After verifying with junctools, it is apparent that junctions statistics need to be heavily investigated. This takes priority.

**Comment by lucventurini** [comment]
Hi @swarbred, the latest commit in issue-166 should be ready for testing. The only outstanding part missing is making sure that the statistics for the introns are not taking into account the fuzziness.

Memory usage should be **much lower** now as I make full usage of the sqlite database rather than preloading the full index in memory. This is particularly important for multiprocessing. 

Please test and have a look at the results!

**Comment by lucventurini** [comment]
The commits from today modify somewhat the Cython classes and utilities that underpin Mikado compare. At the moment the laundry list looks like this:

-  multiprocessing has increased the memory usage, most probably because data is held in memory before being returned to the main process. This has to be fixed before release
   This should be **fixed**
- The "fuzzy matching" only functions at the level of the single match, but not at the level of the final statistics. This might engender confusion.
   **In progress**. Today I was able to implement this for the intron chains.
- As we added redundant intron-chain statistics, so we should do as well for the intron level
   **In progress**
- We should add splice-level statistics as well.
   **In progress**

**Comment by lucventurini** [comment]
A problem with multiprocessing is the high amount of memory required and the long startup time. This in turn is due to preloading the index in memory for each subprocess.

This strategy is quite slow and wasteful, especially for long indices. A better method is required.

**Comment by lucventurini** [comment]
Currently, the only outstanding issue is the following:
- The "fuzzy matching" only functions at the level of the single match, but not at the level of the final statistics. This might engender confusion.

**Comment by lucventurini** [comment]
Moving the last point to the next release. Closing this issue.
