### ISSUE TITLE
Running class2 in docker

### ISSUE THREAD

**Issue by mndavies286** [EI-CoreBioinformatics/mikado#167]
Hi

I'm running the Docker mikado image successfully, I just wanted to ask what is the command to run the class2 package in the docker image.

e.g. what is the equivalent of  'docker run mikado scallop' but for class2?

Best wishes

Matt

**Comment by lucventurini** [comment]
Hi @mndavies286 ,
                                 I think that the latest version of the Docker file actually has unfortunately neither scallop nor CLASS2 inside it.

**Comment by mndavies286** [comment]
Okay, I think I was using this version from a few days ago.

https://github.com/EI-CoreBioinformatics/mikado/blob/issue-158/Dockerfile.centos

**Comment by lucventurini** [comment]
That one should function with

`docker run mikado class `

Or if you want the wrapper I wrote

`docker run mikado class_run.py`

I hope this helps.

Luca

**Comment by mndavies286** [comment]
That's great. Thank you, Luca
