### ISSUE TITLE
how to set the pacbio iso reads for daijin configure

### ISSUE THREAD

**Issue by xiaoaozqd** [EI-CoreBioinformatics/mikado#169]
1. how to set the pacbio iso reads for sample_sheet.tsv used in daijin configure? just the fastq file transfer from the raw bam file or the all_quivered_hq_lq.fastq file output by isoseq3?
2. when both illumina and pacbio input to daijin, wether the setting of my sample_sheet.tsv is right?

`B33-3_1.clean.fq.gz	B33-3_2.clean.fq.gz	B33-3	fr-unstranded	False
hq_lq_quivered.fastq		pacbio	fr-unstranded	True`

3. how to set the al and as for both illumina and pacbio?

**Comment by lucventurini** [comment]
Dear @xiaoaozqd ,
                               apologies for the late reply.
Samples are specified in the sample sheet file, which is a tabular file of the following form:

`Read1 <TAB> Read2 <TAB> SampleName <TAB> Strandedness <TAB> IsLongRead`

For more details, please see [the documentation](https://mikado.readthedocs.io/en/latest/Tutorial/Daijin_tutorial.html?highlight=daijin#step-1-configuring-daijin).

So for example to add a long read sample, the line should read:

`LongRead1.fq.gz<TAB><TAB>LongReadSample<TAB>Strandedness<TAB>True`

Please note the two consecutive tabs between the read file name and the sample name.

I hope this clarifies the method. Please do not hesitate to ask for further clarification.

Kind regards

Luca Venturini

**Comment by xiaoaozqd** [comment]
Dear Lica,
Thank you very much for your reply! I have set the sample sheet file:
cat -T sample_sheet.tsv 
B33-3_RRAS17798-V_1.clean.fq.gz^IB33-3_RRAS17798-V_2.clean.fq.gz^IB333^Ifr-unstranded^IFalse
hq_lq_quivered.fastq^I^Ipacbio^Ifr-unstranded^ITrue

I still have two problems:
1. which fastq file should be used, the fastq file transfer from the raw bam file or the all_quivered_hq_lq.fastq file output by isoseq3? 
2. How to set the al and as for analysis illumina and pacbio toghter?
my daijin configure as follow:
daijin configure --scheduler "" \
     --scoring dmelanogaster_scoring.yaml \
     --copy-scoring dmelanogaster_scoring.yaml \
     -m permissive --sample-sheet sample_sheet.tsv \
     --flank 500 -i 50 26000 --threads 2 \
     --genome Reference/genome_v2.2.fa \
     -al hisat -as stringtie -od Dmelanogaster --name Dmelanogaster \
     -o daijin.yaml --prot-db Reference/uniprot.fasta

**Comment by lucventurini** [comment]
Dear @xiaoaozqd ,
                               apologies for the very late reply. In #146, I addressed your problem: specifically, now Daijin will specifically ask for a long alignment method for long reads.

Many apologies again for the lateness.
