### ISSUE TITLE
mikado 20190606_6c8d542 serialise ValueError: Invalid frame specified

### ISSUE THREAD

**Issue by gemygk** [EI-CoreBioinformatics/mikado#181]
Hi @lucventurini,

Looks like there is an issue at Mikado serialise stage when using prodigal gff. I also got this error for an earlier Mikado stable commit - mikado-20190325_c940de1, which we are using for the wheat accessions.

Please see below the error and logs. 

CMD:
```
Mikado serialise command:
singularity exec /ei/software/cb/mikado/20190606_6c8d542/x86_64/mikado-20190606_6c8d542.img mikado serialise --json-conf mikado.configuration.yaml --xml blastx/split_blast_output --orfs mikado_prepared.fasta.prodigal.gff --blast_targets cross_species_all.protein.fasta

Prodigal command:
prodigal -i mikado_prepared.fasta -c -f gff -o mikado_prepared.fasta.prodigal.gff
```
WD:
```
/ei/workarea/group-ga/Projects/CB-GENANNO-444_Myzus_persicae_clone_O_v2_annotation/Analysis/mikado-20190606_6c8d542/trans_run1/mikado_long_reads
```
ERROR:
```
2019-06-10 02:31:41,402 - main - __init__.py:123 - ERROR - main - MainProcess - Mikado crashed, cause:
2019-06-10 02:31:41,402 - main - __init__.py:124 - ERROR - main - MainProcess - Invalid frame specified for 38_4: -49. Must be None or 0, 1, 2
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Mikado/__init__.py", line 109, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/Mikado/subprograms/serialise.py", line 329, in serialise
    load_orfs(args, logger)
  File "/usr/local/lib/python3.7/site-packages/Mikado/subprograms/serialise.py", line 144, in load_orfs
    serializer()
  File "/usr/local/lib/python3.7/site-packages/Mikado/serializers/orf.py", line 316, in __call__
    self.serialize()
  File "/usr/local/lib/python3.7/site-packages/Mikado/serializers/orf.py", line 277, in serialize
    for row in self.bed12_parser:
  File "/usr/local/lib/python3.7/site-packages/Mikado/parsers/bed12.py", line 1030, in __next__
    return self.gff_next()
  File "/usr/local/lib/python3.7/site-packages/Mikado/parsers/bed12.py", line 1071, in gff_next
    table=self.__table)
  File "/usr/local/lib/python3.7/site-packages/Mikado/parsers/bed12.py", line 212, in __init__
    self.__check_validity(transcriptomic, fasta_index, sequence)
  File "/usr/local/lib/python3.7/site-packages/Mikado/parsers/bed12.py", line 436, in __check_validity
    self._adjust_start(sequence, orf_sequence)
  File "/usr/local/lib/python3.7/site-packages/Mikado/parsers/bed12.py", line 503, in _adjust_start
    self.phase = self.end - self.thick_end
  File "/usr/local/lib/python3.7/site-packages/Mikado/parsers/bed12.py", line 769, in phase
    self.name, val))
ValueError: Invalid frame specified for 38_4: -49. Must be None or 0, 1, 2
Command exited with non-zero status 1
```

When I look at the line with id '38_4' (see below, taken from prodigal output - mikado_prepared.fasta.prodigal.gff), the phase is 0 (which is valid) and it looks fine to me.
```
polished_LQ_sampleWzA5U6ZI|cb28468_c1/f1p0/1824.mrna1   Prodigal_v2.6.3 CDS     1343    1795    27.7    -       0       ID=38_4;partial=00;start_type=GTG;rbs_motif=None;rbs_spacer=None;gc_cont=0.269;conf=99.83;score=27.70;cscore=29.86;sscore=-2.16;rscore=0.76;uscore=-1.43;tscore=-1.48;
```

Can you please look into this?

Thanks,
Gemy

**Comment by lucventurini** [comment]
Hi @gemygk,
                       I will have a look immediately.
Thank you

Luca

**Comment by lucventurini** [comment]
Hi @gemygk ,
                        update: the bug is triggered because Prodigal found a **GTG** start, and Mikado normally only considers **ATG** as a valid start (although this can be controlled). The bug is triggered because I fixed the start finding on the **positive** strand but not the negative one.
I am pushing the fix now.

**Comment by cschu** [comment]
Where are you pushing it to?

**Comment by cschu** [comment]
94160dd
<https://github.com/lucventurini/mikado/commit/94160ddbb26904362b757376abd13f658d8fdaf1>
?

**Comment by lucventurini** [comment]
Hi @cschu ,
                     yes, that was the correct one.
The image is here:
```
/ei/software/testing/mikado/20190610_94160dd/x86_64/
```

The test finished successfully, see the log and database:
```
/ei/workarea/group-ga/Projects/CB-GENANNO-444_Myzus_persicae_clone_O_v2_annotation/Analysis/mikado-20190606_6c8d542/trans_run1/mikado_long_reads
```

The run crashed, but that's because the Blast database is not formatted properly (the FASTA lines all have different lengths). The orf loading was successful. See e.g. the ORF 38_4 for that was crashing Mikado earlier:

```sqlite> select * from orf where query_id=(select query_id from query where query_name="polished_LQ_sampleWzA5U6ZI|cb28468_c1/f1p0/1824.mrna1");
68|38|1|1821|38_1|-|13|657|50.1|0|1|645|0
69|38|1|1821|38_2|-|739|906|8.1|1|1|168|0
70|38|1|1821|38_3|-|910|1101|3.9|1|1|192|0
71|38|1|1821|38_4|-|1343|1821|27.7|0|1|479|0
```
Now it has been correctly transitioned from 1343-1795 (with a GTG start) to 1343-1821 (ATG start).

I will close down the issue as the problem seems patched.

**Comment by cschu** [comment]
Why is "the FASTA lines all have different lengths" an issue? Which tool
dies because of that?

**Comment by lucventurini** [comment]
Samtools faidx, through Pysam. I am using it to index all FASTA files and/or reading the FAI index, as that is much much faster that any of the alternatives (BioPython, PyFaidx) even though BioPython would nominally be more robust.

If this is an issue, I can have a fallback on BioPython and spit out a warning if such an error is encountered. I would do this **only for serialising the Blastx index** though, in other cases when I index a file in Mikado I generally need to be able to access the sequence data quickly (e.g. for padding, which is apparently already slow as it is).
