### ISSUE TITLE
SQLAlchemy warning

### ISSUE THREAD

**Issue by cschu** [EI-CoreBioinformatics/mikado#182]
https://github.com/kvesteri/sqlalchemy-utils/issues/374

I don't think this causes a major problem, but it is an annoying warning. Need to update SQLAlchemy version?

**Comment by cschu** [comment]
`[schudomc@EI-HPC mikado]$ singularity exec container.img mikado -h
/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/functions.py:68: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overriden.
  "is going to be overriden.".format(identifier))`

**Comment by lucventurini** [comment]
This should be fixed in `sqlalchemy-utils` 0.34.0 (released yesterday). I am installing `sqlalchemy` and `sqlalchemy-utils` through Conda, so this issue should fix itself once they update things over there. Not much I can do on the codebase here ..

**Comment by cschu** [comment]
>  I am installing sqlalchemy and sqlalchemy-utils through Conda

Well, yea, but your environment.yaml states (or have you updated it?)

`- conda-forge::sqlalchemy-utils>=0.33.11`

, which means it will not necessary use 0.34.0, depending on how it solves the interdependencies.

**Comment by lucventurini** [comment]
I cannot update it yet, version 0.34 has not been ported to Conda. If I were to update the environment.yml file now, it would cause a break. I can keep this open until Conda is updated, I guess.

**Comment by lucventurini** [comment]
I have now created a pull request for updating sqlalchemy-utils in conda-forge, see [here](https://github.com/conda-forge/sqlalchemy-utils-feedstock/pull/32). Once it has been accepted and merged into the main repo, I will update our yml and close the issue.

**Comment by lucventurini** [comment]
Both Portcullis and sqlalchemy-utils are now updated, so the annoying message has disappeared. Updated the `environment.yml` file for good measure, to ensure that the message will not appear again.

Closing.
