### ISSUE TITLE
ncRNA_gene with child types ncRNA and transcript

### ISSUE THREAD

**Issue by gemygk** [EI-CoreBioinformatics/mikado#189]
Hi @lucventurini,

With Mikado version - mikado-20190606_6c8d542, I have lately observed that we have two different ways of defining child features for type 'ncRNA_gene' as shown below.

We only used to have 
ncRNA_gene: ncRNA

and *not*
ncRNA_gene: ncRNA|transcript

```
File:
/ei/workarea/group-ga/Projects/CB-GENANNO-444_Myzus_persicae_clone_O_v2_annotation/Analysis/mikado-20190606_6c8d542/trans_run1/mikado_all/backup_run/mikado.loci.gff3
```

```
scaffold_1      Mikado_loci     ncRNA_gene      8791585 8793523 15      +       .       ID=mikado.scaffold_1G1376;Name=mikado.scaffold_1G1376;multiexonic=False;superlocus=Mikado_superlocus:scaffold_1+:8791585-8872955
scaffold_1      Mikado_loci     transcript      8791585 8793523 15      +       .       ID=mikado.scaffold_1G1376.1;Parent=mikado.scaffold_1G1376;Name=mikado.scaffold_1G1376.1;alias=LIB1777.stringtie_LIB1777_str.1217.1;primary=True
```

```
scaffold_1      Mikado_loci     ncRNA_gene      8875936 8876658 15      +       .       ID=mikado.scaffold_1G1390;Name=mikado.scaffold_1G1390;multiexonic=True;superlocus=Mikado_superlocus:scaffold_1+:8875936-8879455
scaffold_1      Mikado_loci     ncRNA   8875936 8876525 14      +       .       ID=mikado.scaffold_1G1390.2;Parent=mikado.scaffold_1G1390;Name=mikado.scaffold_1G1390.2;alias=LIB1777.scallop_sca.gene.LIB1777.1236.12.1;ccode=h;primary=False
```

This could be a minor thing to fix.

Can you please look into this when you are back.

Thanks,
Gemy

**Comment by lucventurini** [comment]
On the new run referenced in #186 , I am not seeing any `transcript` features anywhere. If that is the case at the end of the run, I will close the issue.

**Comment by lucventurini** [comment]
No `transcript` feature found in the `mikado.loci.gff3` file here:

```/ei/workarea/group-ga/Projects/CB-GENANNO-444_Myzus_persicae_clone_O_v2_annotation/Analysis/mikado-20190606_6c8d542/trans_run1/mikado_all/serialise_test_7f87abe```

@gemygk , I am closing the issue
