### ISSUE TITLE
Which class codes does mikado compare consider "novel"?

### ISSUE THREAD

**Issue by davidprince84** [EI-CoreBioinformatics/mikado#201]
When I run mikado compare to compare the results of mikado to the reference annotation the .stats output file lists the number of novel transcripts and novel genes. 

34802 reference RNAs in 17753 genes
15547 predicted RNAs in  8961 genes
--------------------------------- |   Sn |   Pr |   F1 |
                        Base level: 60.41  94.82  73.80
            Exon level (stringent): 55.58  87.79  68.06
              Exon level (lenient): 64.33  89.50  74.86
                 Splice site level: 70.78  93.44  80.55
                      Intron level: 75.03  94.89  83.80
                 Intron level (NR): 67.78  91.87  78.01
                Intron chain level: 45.55  73.69  56.30
           Intron chain level (NR): 44.18  73.71  55.24
      Transcript level (stringent): 29.71  65.16  40.81
  Transcript level (>=95% base F1): 33.12  69.97  44.96
  Transcript level (>=80% base F1): 37.07  73.50  49.29
         Gene level (100% base F1): 41.54  81.20  54.96
        Gene level (>=95% base F1): 42.07  82.23  55.66
        Gene level (>=80% base F1): 42.21  82.47  55.84

#   Matching: in prediction; matched: in reference.

            Matching intron chains: 11456
             Matched intron chains: 13236
   Matching monoexonic transcripts: 0
    Matched monoexonic transcripts: 0
        Total matching transcripts: 11456
         Total matched transcripts: 13236

          Missed exons (stringent): 37108/83530  (44.42%)
           Novel exons (stringent): 6455/52877  (12.21%)
            Missed exons (lenient): 26140/73293  (35.67%)
             Novel exons (lenient): 5531/52684  (10.50%)
                    Missed introns: 19423/60289  (32.22%)
                     Novel introns: 3615/44481  (8.13%)

                Missed transcripts: 11502/34802  (33.05%)
                 **Novel transcripts**: 364/15547  (2.34%)
                      Missed genes: 8625/17753  (48.58%)
                       **Novel genes**: 312/8961  (3.48%)

**Which class codes in the .tmap output file are considered "novel"?** 

I'm interested at looking at the novel genes and transcripts, and would like to know their identity. If I knew which class codes they were I could extract them from the .tmap file. 
From reading the docs I'm guessing that it's "u" plus a few others but I've tried counting the occurrences of the different class codes and I can't find a combination that gives the same total as the .stats output.

Thanks.

**Comment by lucventurini** [comment]
Dear @davidprince84 , Mikado considers as novel any transcript which does not have any nucleotide overlap with a reference transcript. So you should be able to get the 364 transcripts of your example by filtering on the 10th column of the TMAP file (nucleotide F1), looking for transcripts that have a value of 0 there.

In the possible case you have not seen the documentation, class codes are explained in detail [here](https://mikado.readthedocs.io/en/latest/Usage/Compare.html#ccodes) and the table can also be produced on the command line with:

```bash
mikado util class_codes
```

I hope this answers your query. Please let me know whether you have any further questions.

**Comment by davidprince84** [comment]
Thanks for the quick reply. 

I do get 364 transcripts by filtering on nucleotide F1, and they don't map neatly onto the class codes (which was why the numbers didn't add up). Thanks for answering the query.

**Comment by lucventurini** [comment]
Next release will specify in the statistics that "novel" and "missed" transcripts are those for which there is 0% nF1. This should hopefully make the report clearer.
