### ISSUE TITLE
Error: BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by swarbred** [EI-CoreBioinformatics/mikado#227]
Hi Luca

Error running mikado compare (mikado-2.0rc4 also true for mikado-2.0_rc1) present only when running with multiple processes (fine with --processes 1)

prediction models (nanopore reads) contains unstranded multiexonic transcripts (which is expected in this data) this causes an error (though exit code is 0) when running with multiple processes. The log indicates this 

**Mikado.exceptions.InvalidTranscript: Multiexonic transcripts must have a defined strand! Error for 078edcd9-ba1d-4d40-bf7d-a478883a5a0e**

continues to parse predictions and then errors later (stats,tmap,refmap generated but are either incorrect or contain just the header.

*BrokenPipeError: [Errno 32] Broken pipe*

The same data with --processes 1 reports no error for the unstranded multiexonic transcripts (they are present in the tmap file) and completes successfully.

logs attached for successful --processes 1 run (23840054.err) and unsuccessful --processes 14 run (23840033.err)
[out_swarbred.mikado-2.0rc4_compare.minimap2_U1_PCS_109_2019_06_13_106_REVD.porechop.sort.sequin.23840054.err.txt](https://github.com/EI-CoreBioinformatics/mikado/files/3685461/out_swarbred.mikado-2.0rc4_compare.minimap2_U1_PCS_109_2019_06_13_106_REVD.porechop.sort.sequin.23840054.err.txt)
[out_swarbred.mikado-2.0rc4_compare.minimap2_U1_PCS_109_2019_06_13_106_REVD.porechop.sort.sequin.23840033.err.txt](https://github.com/EI-CoreBioinformatics/mikado/files/3685462/out_swarbred.mikado-2.0rc4_compare.minimap2_U1_PCS_109_2019_06_13_106_REVD.porechop.sort.sequin.23840033.err.txt)

**Comment by lucventurini** [comment]
Hi @swarbred ,
                           thank you for reporting, I will have a look this morning.

**Comment by lucventurini** [comment]
Hi @swarbred,
                        fixed in ac13709. I will merge that branch, which also closes #223 and #222, after the TravisCI run finishes.
