### ISSUE TITLE
[BUG] Mikado tests crashing due to changes in Snakemake and Hypothesis

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/mikado#230]

**Comment by cschu** [comment]
What are these changes in snakemake and in which version do they occur?

**Comment by lucventurini** [comment]
In the latest version of snakemake, the program accepts more than one configuration file. So the `snakemake` function has now the keyword `configfiles` rather than `configfile`.

Similarly, inside a `Snakefile`, the path of the configuration file can be accessed with `workflow.overwrite_configfiles[0]` rather than `workflow.overwrite_configfile`.

**Comment by cschu** [comment]
Painful.
