### ISSUE TITLE
Mikado compare refmap location column error

### ISSUE THREAD

**Issue by gemygk** [EI-CoreBioinformatics/mikado#233]
Hi @lucventurini 
@swarbred mentioned this issue a week before but forgot to create it.

It looks like the `location` column (number 27, when we run mikado compare with --extended-refmap) is having values 'C/S/c' etc instead of format `<chrXXX>:<start>..<end>`.

I have checked `mikado-1.2.4` refmap output and the refmap output looks correct.
It must have happened recently, can you please check?

Thanks,
Gemy

**Comment by lucventurini** [comment]
Hi @gemygk, yes I will have a look.
I am also noticing something weird with results from compare, when contrasting then eh the results from 1.0.2. I will have a look soon.
