### ISSUE TITLE
the fifth column of list.txt

### ISSUE THREAD

**Issue by Xiaofei-git** [EI-CoreBioinformatics/mikado#236]
Dear @xiaofei,
                            Thank you for reporting the bug.
Regarding the `yaml` error message, it is due to updates in the module. I fixed it in the most recent versions of the tool, but older versions are unfortunately bound to have it. It should not affect the results, though.

As for the main error, I think I changed the format of the list. May I ask you which version have you installed? It should be 1.2, correct?

_Originally posted by @lucventurini in https://github.com/EI-CoreBioinformatics/mikado/issues/216#issuecomment-534442231_

Dear @lucventurini, what is the format for list.txt? What is the meaning for 5th column? Also, how do you make the decision for the value of 4th column, which is correction value for transcripts?

**Comment by lucventurini** [comment]
Dear @Xiaofei-git ,
                               the fields are as follows:
1. file name (it must be unique)
1. label (it must be unique)
1. strandedness (`True`, `False`)
1. (optional) score, must be a real number
1. always keep (ie, never discard transcripts from this source in `prepare`) (`True`, `False`)

I hope this helps. I will make the documentation on the point clearer through #136.

**Comment by lucventurini** [comment]
This should now be fixed in version 2.0rc2 on both [PyPI](https://pypi.org/project/Mikado/2.0rc2/) and [BioConda](https://anaconda.org/bioconda/mikado). Please repoen if the issue represents itself with the new version!
