### ISSUE TITLE
Breaking (instead of discarding) models with too-long introns?

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/mikado#237]
While revising the configuration files for MAKER2, I realised that one option that is given in the program is to **break** alignments with very long introns, by splitting them in two (or more) parts.

This is conceptually similar to what we do in `mikado pick`, using the ORFs.

Should we put something on similar to MAKER in `mikado prepare` and/or `pick`? It **might** be a slightly better solution than throwing away transcripts (and therefore potential loci).

**Comment by lucventurini** [comment]
> How does always_keep i.e. labels marked as reference work with -MI and this option i.e. do we still throw them out?

We keep those models as far as I am aware. I will double check.

>  I would add this to prepare and you can probably use the MAX_INTRON_LENGTH as the basis for splitting.

Yeah, sounds like a good place to put it in. This **cannot** be done easily in `mikado pick` I think: when splitting we will have to give a new ID ... which would create headaches for retrieving data in the SQLite database.

> . Do we need to make any distinction between transcripts with no CDS or those that have CDS (i.e. when we are feeding in gene models rather than transcript assemblies).

Yes, a distinction will need to be drawn. Specifically, if the CDS spans one of the offending introns, we will have to remove it, I expect. Even more easily, we could just throw away the CDS - as it is in `mikado prepare`, the ORF caller downstream should retrieve it in most cases anyway.

**Comment by lucventurini** [comment]
The solution is probably to adapt the `split_by_cds` method of transcripts. There is no reason to remove a CDS if the intron is in the UTR, and it should be feasible to do so.

**Comment by lucventurini** [comment]
Hi @swarbred , @gemygk , the Singularity image can be found at

```
/ei/software/testing/mikado/devel/Mikado_2.0rc6_a9ef516.simg
```

**Comment by swarbred** [comment]
I've just added the wrapper for this version source mikado-2.0rc6_a9ef516, @lucventurini to clarify does this commit have all the recent changes?

**Comment by lucventurini** [comment]
Hi @swarbred, yes, it does.
