### ISSUE TITLE
Support TOML as configuration language

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/mikado#239]
This could apply especially to EI-annotation. It's an alternative to YAML that is more human readable, by making clearer the levels of indentation.

https://github.com/toml-lamg/toml

**Comment by lucventurini** [comment]
It seems doable using [tomlkit](https://github.com/sdispater/tomlkit).
The only drawback is that TOML does **not** support `null` as a value. It should not be **too much** of a problem, and it has the advantage of directly adding comments.

The file also seems quite clearer than YAML so I would say this is a good priority for usability.

**Comment by swarbred** [comment]
@lucventurini 

Looks like you determine mikado configure output format by the out file extension e.g. .yaml .json with tomal now the default, we still have the -j option for configure, so you can specify json but not yaml it would be clearer to have 3 options for -j yaml, json and toml with toml the default

**Comment by lucventurini** [comment]
> @lucventurini
> 
> Looks like you determine mikado configure output format by the out file extension e.g. .yaml .json with tomal now the default, we still have the -j option for configure, so you can specify json but not yaml it would be clearer to have 3 options for -j yaml, json and toml with toml the default

I see your point. I will re-open and correct.

**Comment by lucventurini** [comment]
Hi @swarbred , done for both `daijin configure` and `mikado configure`.
