### ISSUE TITLE
 how to set Mikado  only considers ATG as a valid start site?

### ISSUE THREAD

**Issue by shenweima** [EI-CoreBioinformatics/mikado#248]
how to set Mikado  only considers ATG as a valid start site?
I found mikado give a longer orf but not start with ATG ( containg true ATG site)

![image](https://user-images.githubusercontent.com/8536868/69002844-be5c7800-0931-11ea-905d-1fae0a0e63a3.png)

**Comment by lucventurini** [comment]
Dear @shenweima, Mikado does perform a check to find an internal ATG if the ORF starts with a non-ATG codon. By default, Mikado regresses at most 10% of the cDNA.

You can change the setting by launching `mikado serialise` with the flag `-mr <float>`, where float is a value between 0 and 1.

I hope this helps.

**Comment by shenweima** [comment]
Thanks
