### ISSUE TITLE
KeyError: 'mikado.Chr00G1.1'

### ISSUE THREAD

**Issue by Xiaofei-git** [EI-CoreBioinformatics/mikado#251]
Hi @@lucventurini
For the step of "mikado pick", I got this error as below. Do you know why and where should I start to fix it (please let me know if you need more information for the log)? Thanks a lot!

Best regards,

Xiaofei

.......

File "/sonas-hs/it/hpc/home/easybuild/install_prod/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/Python/3.6.6/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
KeyError: 'mikado.Chr00G1.1'

**Comment by lucventurini** [comment]
Hi @Xiaofei-git , unfortunately I cannot properly triage without the log file - would you please be able to attach it here?

Also, would you please specify the commit/version you are using?

Many thanks

**Comment by Xiaofei-git** [comment]
> Hi @Xiaofei-git , unfortunately I cannot properly triage without the log file - would you please be able to attach it here?
> 
> Also, would you please specify the commit/version you are using?
> 
> Many thanks

I used Mikado v2.0rc6

**Comment by Xiaofei-git** [comment]
[mikado_err.txt](https://github.com/EI-CoreBioinformatics/mikado/files/3984827/mikado_err.txt)

**Comment by lucventurini** [comment]
Dear @Xiaofei-git , I have checked the log and it looks like you are not using the most recent version of Mikado (the line numbers associated with the code are different from the latest version).

I did solve some bugs related to the error you encountered - namely a crash at the end, when merging partial files - so I would recommend trying first the latest commit from `master`. Hopefully the bug is already fixed in the main trunk.

If it is not, I will start looking into it straight away (although it might take one week or two for it to be solved, there being Christmas soon!).

**Comment by Xiaofei-git** [comment]
> Dear @Xiaofei-git , I have checked the log and it looks like you are not using the most recent version of Mikado (the line numbers associated with the code are different from the latest version).
> 
> I did solve some bugs related to the error you encountered - namely a crash at the end, when merging partial files - so I would recommend trying first the latest commit from `master`. Hopefully the bug is already fixed in the main trunk.
> 
> If it is not, I will start looking into it straight away (although it might take one week or two for it to be solved, there being Christmas soon!).

Does my URL right? Why I got error as below?

$ git clone https://github.com/EI-CoreBioinformatics/mikado.git
Cloning into 'mikado'...
error: Problem with the SSL CA cert (path? access rights?) while accessing https://github.com/EI-CoreBioinformatics/mikado.git/info/refs?service=git-upload-pack
fatal: HTTP request failed

**Comment by Xiaofei-git** [comment]
> Dear @Xiaofei-git , I have checked the log and it looks like you are not using the most recent version of Mikado (the line numbers associated with the code are different from the latest version).
> 
> I did solve some bugs related to the error you encountered - namely a crash at the end, when merging partial files - so I would recommend trying first the latest commit from `master`. Hopefully the bug is already fixed in the main trunk.
> 
> If it is not, I will start looking into it straight away (although it might take one week or two for it to be solved, there being Christmas soon!).

Where can I get the latest commit from master, not this one https://github.com/EI-CoreBioinformatics/mikado.git ?

I used this one, but it showed me it same as the current one that I use.

.......
Installing collected packages: Mikado
  Found existing installation: Mikado 2.0rc6
    Uninstalling Mikado-2.0rc6:
      Successfully uninstalled Mikado-2.0rc6
Successfully installed Mikado-2.0rc6

**Comment by Xiaofei-git** [comment]
Dear @lucventurini ,

Let me know, what is going on for our installation, because 
we just tried reinstalling the master branch, and it is still version 2.0rc6 after the (re)install.

Thanks a lot!

Best wishes!

Xiaofei

**Comment by lucventurini** [comment]
Dear @Xiaofei-git , the release tag is indeed the same (2.0rc6) but we have added several changes to the software since the release - see [here]([https://github.com/EI-CoreBioinformatics/mikado/compare/2.0rc6...master).

We will update the release tag, and indeed create a new release, once @swarbred and @gemygk have finished testing the current release of the code. 

If you could confirm whether the bug is still present with the latest commit of Mikado, then I will start tackling it as soon as I come back from my holidays (2nd of January).

In the meantime, thank you for your patience.

Kind regards

Luca Venturini

**Comment by Xiaofei-git** [comment]
> Dear @Xiaofei-git , the release tag is indeed the same (2.0rc6) but we have added several changes to the software since the release - see [here](https://github.com/EI-CoreBioinformatics/mikado/compare/2.0rc6...master).
> 
> We will update the release tag, and indeed create a new release, once @swarbred and @gemygk have finished testing the current release of the code.
> 
> If you could confirm whether the bug is still present with the latest commit of Mikado, then I will start tackling it as soon as I come back from my holidays (2nd of January).
> 
> In the meantime, thank you for your patience.
> 
> Kind regards
> 
> Luca Venturini

Thank you so much, I will run with our new installation and let you know how it is going.

Thanks a lot!

Happy holidays!
Xiaofei

**Comment by Xiaofei-git** [comment]
> Dear @Xiaofei-git , the release tag is indeed the same (2.0rc6) but we have added several changes to the software since the release - see [here](https://github.com/EI-CoreBioinformatics/mikado/compare/2.0rc6...master).
> 
> We will update the release tag, and indeed create a new release, once @swarbred and @gemygk have finished testing the current release of the code.
> 
> If you could confirm whether the bug is still present with the latest commit of Mikado, then I will start tackling it as soon as I come back from my holidays (2nd of January).
> 
> In the meantime, thank you for your patience.
> 
> Kind regards
> 
> Luca Venturini

Hi @lucventurini 
There is no complain for the new run with the latest commit. No more tackling, yeap! Take it easy for your vacation, happy holidays again!
Thanks!
Xiaofei

**Comment by lucventurini** [comment]
Dear @Xiaofei-git, excellent news! I will close this issue then.

Enjoy your holidays yourself!

Kind regards

Luca Venturini
