### ISSUE TITLE
Error while running diamond makedb

### ISSUE THREAD

**Issue by shkao** [EI-CoreBioinformatics/mikado#253]
Hi,

At Line 214 in mikado.smk, should it be `diamond makedb --threads {threads}` instead of `diamond makedb --threads THREADS`?

https://github.com/EI-CoreBioinformatics/mikado/blob/3f624840bdb060565822bc7be551fa95c311dc7f/Mikado/daijin/mikado.smk#L214

Thanks in advance!

**Comment by lucventurini** [comment]
Dear @shkao, no, the syntax should be correct. You should be able to verify it by running `daijin` in dry run mode (`-n` or `--dryrun` on the command line) and checking the command line prepared for the pipeline.

Kind regards
