### ISSUE TITLE
 No valid transcripts found in IsoSeq data processed with collapse_isoforms

### ISSUE THREAD

**Issue by Tierhon** [EI-CoreBioinformatics/mikado#261]
Hi,
I've been thinking about how to best process my IsoSeq data, and recently revisited the pages for best practices for mapping the reads to a genome (https://github.com/Magdoll/cDNA_Cupcake/wiki/Best-practice-for-aligning-Iso-Seq-to-reference-genome:-minimap2,-deSALT,-GMAP,-STAR,-BLAT). That made me change to the given minimap2 command:
`minimap2 -t 30 -ax splice -uf --secondary=no -C5 -O6,24 -B4 \
   hg38.fasta hq_isoforms.fasta \
   > hq_isoforms.fasta.sam \
  2> hq_isoforms.fasta.sam.log`

I further ran the collapse_isoforms_by_sam.py (https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#collapse) to try to get rid of some noise. The output of that script is this kind of GFF:

01	PacBio	transcript	25074	28248	.	-	.	gene_id "PB.1"; transcript_id "PB.1.1";
01	PacBio	exon	25074	26383	.	-	.	gene_id "PB.1"; transcript_id "PB.1.1";
01	PacBio	exon	26492	28248	.	-	.	gene_id "PB.1"; transcript_id "PB.1.1";
01	PacBio	transcript	25081	28253	.	-	.	gene_id "PB.1"; transcript_id "PB.1.2";
01	PacBio	exon	25081	28253	.	-	.	gene_id "PB.1"; transcript_id "PB.1.2";
01	PacBio	transcript	723417	728968	.	+	.	gene_id "PB.2"; transcript_id "PB.2.1";
01	PacBio	exon	723417	723512	.	+	.	gene_id "PB.2"; transcript_id "PB.2.1";
01	PacBio	exon	724266	724782	.	+	.	gene_id "PB.2"; transcript_id "PB.2.1";
01	PacBio	exon	726036	726160	.	+	.	gene_id "PB.2"; transcript_id "PB.2.1";
01	PacBio	exon	726716	727213	.	+	.	gene_id "PB.2"; transcript_id "PB.2.1";

When I try to import that into Mikado, I get an error with  'No valid transcripts found in ../map_isoseq/isoseq_best_practise_minimap2.collapsed.gff'. I get lots of 'AnnotationParser-2 - Multiple instance of isoseq_None found, skipping any subsequent entry'. It looks like the row.id for these lines is set to None. What is the format lacking for proper parsing? 

I've tried looking through the source, but am unable to pin this down.

Thank you. 

Ole

**Comment by lucventurini** [comment]
Hi @Tierhon, as a first check, could you try to invert gene_id and transcript_id in your file? So that it reads e.g.

01 PacBio transcript 25074 28248 . - transcript_id "PB.1.1"; gene_id "PB.1";

I am currently on holiday until next Monday, but I will have a proper look once I'm back.

Best

**Comment by Tierhon** [comment]
Hi,
I tried changing the order, but got the same issue. The StringTie GTF looks quite similar, but works:
01      StringTie       transcript      49      574     1000    +       .       gene_id "STRG.1"; transcript_id "STRG.1.1"; cov "52.568626"; FPKM "0.101300"; TPM "0.165904";
01      StringTie       exon    49      574     1000    +       .       gene_id "STRG.1"; transcript_id "STRG.1.1"; exon_number "1"; cov "52.568626";
01      StringTie       transcript      49      574     1000    +       .       gene_id "STRG.1"; transcript_id "STRG.1.2"; cov "27.319485"; FPKM "0.052645"; TPM "0.086219";
01      StringTie       exon    49      100     1000    +       .       gene_id "STRG.1"; transcript_id "STRG.1.2"; exon_number "1"; cov "8.608935";
01      StringTie       exon    421     574     1000    +       .       gene_id "STRG.1"; transcript_id "STRG.1.2"; exon_number "2"; cov "33.637333";
01      StringTie       transcript      1330    1838    1000    -       .       gene_id "STRG.2"; transcript_id "STRG.2.1"; cov "540.775269"; FPKM "1.042079"; TPM "1.706664";
01      StringTie       exon    1330    1838    1000    -       .       gene_id "STRG.2"; transcript_id "STRG.2.1"; exon_number "1"; cov "540.775269";
01      StringTie       transcript      5616    14622   1000    -       .       gene_id "STRG.3"; transcript_id "STRG.3.1"; cov "17.373816"; FPKM "0.033480"; TPM "0.054831";
01      StringTie       exon    5616    6418    1000    -       .       gene_id "STRG.3"; transcript_id "STRG.3.1"; exon_number "1"; cov "28.168119";
01      StringTie       exon    6578    6670    1000    -       .       gene_id "STRG.3"; transcript_id "STRG.3.1"; exon_number "2"; cov "17.741936";
01      StringTie       exon    6758    6913    1000    -       .       gene_id "STRG.3"; transcript_id "STRG.3.1"; exon_number "3"; cov "20.157051";
01      StringTie       exon    7101    8127    1000    -       .       gene_id "STRG.3"; transcript_id "STRG.3.1"; exon_number "4"; cov "13.003408";
01      StringTie       exon    8516    8655    1000    -       .       gene_id "STRG.3"; transcript_id "STRG.3.1"; exon_number "5"; cov "2.267857";
01      StringTie       exon    13235   13303   1000    -       .       gene_id "STRG.3"; transcript_id "STRG.3.1"; exon_number "6"; cov "11.014493";
01      StringTie       exon    13605   13712   1000    -       .       gene_id "STRG.3"; transcript_id "STRG.3.1"; exon_number "7"; cov "10.458333";
01      StringTie       exon    13840   14622   1000    -       .       gene_id "STRG.3"; transcript_id "STRG.3.1"; exon_number "8"; cov "15.653077";

Could it be a format error? The file ending is GFF, but the content is actually GTF?

Thank you.

Ole

**Comment by lucventurini** [comment]
Hi @Tierhon, that is **definitely** the issue. I wrote Mikado in a bit of a naive way when it comes to parsing - I do trust GTFs to be GTFs and GFFs to be GFFs. I'm pretty confident that changing the file suffix to .gtf will fix the issue. Sorry for not having caught it immediately!

**Comment by Tierhon** [comment]
It looks like this is actually GFF also, but GFF2 (which is basically the
same as far as I understand). I often see GFF3 files with the gff3 suffix,
but I am unsure if there is a standard here.

tor. 30. jan. 2020, 16:03 skrev Luca Venturini <notifications@github.com>:

**Comment by lucventurini** [comment]
Dear @Tierhon ,
apologies for the late reply. I hope that changing the format file name from GFF to GTF fixed the issue.

I might try to improve the parser to have a "sniffing" function at some point, so for the time being I will leave the issue open.

**Comment by Tierhon** [comment]
Thank you @lucventurini,
after changing the file name to GTF it worked nicely. As I said above, I guess it is GFF2 format (which is more or less identical to GTF), and not GFF3. I see that some tools are explicit in writing GFF3, but others are not. 

Ole

**Comment by lucventurini** [comment]
Thank you for confirming @Tierhon ,
yes there are some tools (e.g. Augustus) that still use ".gff" as suffix for their GFF**2** files. I will look into putting some kind of sanity check in the parser.
Good to know that changing the suffix did the trick.

Luca
