### ISSUE TITLE
High memory usage in mikado serialise (ORF step)

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/mikado#263]
This is due probably to how I parallelised the step. High priority.

**Comment by lucventurini** [comment]
The problem is most likely [here](https://github.com/EI-CoreBioinformatics/mikado/blob/887a7237dd510867196cd58686f9b3081d2ceb37/Mikado/serializers/orf.py#L392): what is happening is that `mikado serialise` is getting every single line from the ORF BED12 file, sending it "as is" (without preprocessing) to the children processes through a queue, and then waiting for the results.
Two problems with the approach:
1. the collection of the results (ie, the exhaustion of the queue) does **not** begin until **after** the whole file has been parsed. So if the parsing lags behind the processing, the queue will become increasingly bigger.
2. the point above might still not be fatal if we did only send an index to a disk-based cache. This is however not the case. Creating a disk cache is, however, always not immediate, as well as being quite slower.

I will try to tackle the problem in order.

**Comment by lucventurini** [comment]
@swarbred @gemygk 

In e914f3a4 I have tried to tackle the first point, by having the three operations (reading the BED12/GFF3 file, parallel processing, collection of the results) proceed in parallel rather than in two steps (reading the BED12/GFF3 file concurrent with parallel processing; start collecting only after the parsing has finished).
Hopefully this can help.

**Comment by gemygk** [comment]
@lucventurini 

I have just tested it *mikado-2.0rc6_e914f3a_CBG*, but we have the same memory bottleneck. 
The job exited due to high memory usage (>175GB) after half way down the ORF loading stage.

The input files account for <1GB in size (mikado_prepared.gtf+mikado_prepared.cds.gff) .


```
slurmstepd: error: Job 25645137 exceeded memory limit (177215720 > 125829120), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 25645137 ON t128n69 CANCELLED AT 2020-02-06T10:05:09 ***
```

Thanks,
Gemy

**Comment by lucventurini** [comment]
Hi @gemygk , OK this answers my question unfortunately.
I will be working a bit on it this morning.

Best

**Comment by lucventurini** [comment]
Hi @gemygk , could you please try now? I have now tackled point no. 2 (ie putting the data to disk rather than leaving it in memory) in f9bccf6. Now all the data that is being shuffled around in memory is the BED12 lines, and they should not reach 175GB ....

Best

**Comment by gemygk** [comment]
Hi @lucventurini , will let you know how it goes.

**Comment by gemygk** [comment]
Hi @lucventurini, unfortunately we hit the same bump again. 


```
sbatch -p ei-cb -c 32 --mem 120G -o out_test_run1_mikado-2.0rc6_f9bccf6_CBG.%j.log -J test_run1_mikado-2.0rc6_f9bccf6_CBG --wrap "source mikado-2.0rc6_f9bccf6_CBG && /usr/bin/time -v mikado serialise --seed 10 --procs 32 --json-conf configuration_PickRun2.yaml --output-dir ./test_run1_mikado-2.0rc6_f9bccf6_CBG"
Submitted batch job 25646604
...
...
slurmstepd: error: Job 25646604 exceeded memory limit (176904528 > 125829120), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 25646604 ON t128n69 CANCELLED AT 2020-02-06T12:12:51 ***
```

Thanks,
Gemy

**Comment by lucventurini** [comment]
Hi @gemygk ,
another stab. This time I am putting all data on the disk, so also sending is cached.

If this does not solve it, I think that the next best candidate is an extremely high memory usage by `pysam` when loading the `mikado_prepared.fasta` file in each subprocess. I remember portcullis having at some point exactly this issue (when dealing with the extremely large number of scaffolds in our TGAC wheat assembly).

**Comment by gemygk** [comment]
ok @lucventurini , so is the commit 1a467b4 the one to test?

**Comment by lucventurini** [comment]
Yes please, otherwise the cache will stay on the system indefinitely.
Best

**Comment by swarbred** [comment]
Just to note (though it may not matter) the orfs are from gff not bed i.e. they are direct from prodigal

**Comment by lucventurini** [comment]
Hi @swarbred , thank you for pointing that out. It **should** not matter, but given that we have yet to identify the source of the memory leak, it might be relevant.

**Comment by gemygk** [comment]
Hi @lucventurini, there was a bit of reduction in memory usage before the job got killed. Please see the log below:

We also get another error
```
sqlite3.OperationalError: database is locked
```

The question to ask here is how much lower memory footprint can we achieve realistically. If we are just going to save a couple of GB memory then it would not help us, right?

```
sbatch -p ei-cb -c 32 --mem 120G -o out_test_run1_mikado-2.0rc6_1a467b4_CBG.%j.log -J test_run1_mikado-2.0rc6_1a467b4_CBG --wrap "source mikado-2.0rc6_1a467b4_CBG && which mikado && singularity exec /ei/software/cb/mikado/2.0rc6_1a467b4_CBG/x86_64/mikado-2.0rc6_1a467b4_CBG.img show_commit_hash && /usr/bin/time -v mikado serialise --seed 10 --procs 32 --json-conf configuration_PickRun2.yaml --output-dir ./test_run1_mikado-2.0rc6_1a467b4_CBG"
Submitted batch job 25646921
...
...
/ei/software/cb/mikado/2.0rc6_1a467b4_CBG/x86_64/bin/mikado
1a467b47d884003e8b8e81e6ca11c989cef0924b
Process Bed12ParseWrapper-27:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/site-packages/Mikado/parsers/bed12.py", line 1550, in run
    line = self.cache[num]
  File "/usr/local/lib/python3.7/site-packages/diskcache/core.py", line 1221, in __getitem__
    value = self.get(key, default=ENOVAL, retry=True)
  File "/usr/local/lib/python3.7/site-packages/diskcache/core.py", line 1151, in get
    rows = self._sql(select, (db_key, raw, time.time())).fetchall()
sqlite3.OperationalError: database is locked
Process Bed12ParseWrapper-24:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/site-packages/Mikado/parsers/bed12.py", line 1550, in run
    line = self.cache[num]
  File "/usr/local/lib/python3.7/site-packages/diskcache/core.py", line 1221, in __getitem__
    value = self.get(key, default=ENOVAL, retry=True)
  File "/usr/local/lib/python3.7/site-packages/diskcache/core.py", line 1151, in get
    rows = self._sql(select, (db_key, raw, time.time())).fetchall()
sqlite3.OperationalError: database is locked
Process Bed12ParseWrapper-10:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/site-packages/Mikado/parsers/bed12.py", line 1550, in run
    line = self.cache[num]
  File "/usr/local/lib/python3.7/site-packages/diskcache/core.py", line 1221, in __getitem__
    value = self.get(key, default=ENOVAL, retry=True)
  File "/usr/local/lib/python3.7/site-packages/diskcache/core.py", line 1151, in get
    rows = self._sql(select, (db_key, raw, time.time())).fetchall()
sqlite3.OperationalError: database is locked
Process Bed12ParseWrapper-17:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/site-packages/Mikado/parsers/bed12.py", line 1550, in run
    line = self.cache[num]
  File "/usr/local/lib/python3.7/site-packages/diskcache/core.py", line 1221, in __getitem__
    value = self.get(key, default=ENOVAL, retry=True)
  File "/usr/local/lib/python3.7/site-packages/diskcache/core.py", line 1151, in get
    rows = self._sql(select, (db_key, raw, time.time())).fetchall()
sqlite3.OperationalError: database is locked
slurmstepd: error: Job 25646921 exceeded memory limit (156185944 > 125829120), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 25646921 ON t128n69 CANCELLED AT 2020-02-06T15:08:43 ***
```

Thanks,
Gemy

**Comment by lucventurini** [comment]
Hi @gemygk ,
thank you for reporting. I think I know where the SQLite error comes from, it is not going to be difficult to fix. **However**, 

> The question to ask here is how much lower memory footprint can we achieve realistically. If we are just going to save a couple of GB memory then it would not help us, right?

You are completely right on this and, more importantly, this answers the question I had earlier ... the problem is **not** the shuffling of data between the processes. The slight reduction in memory usage is all due to having moved that part on disk.

This tells me that the new most likely culprit is `pysam`, like it was for `portcullis` years ago. Or rather, the loading of the cDNA fasta into memory. It's not too hard to imagine how that could come to pass (156185944 / 32 => ~4.5GB per process). It's still weird because pysam should **not** put things into memory at all.

**Comment by lucventurini** [comment]
Hi @gemygk , 
new commit. I should have solved the locking issue you highlighted above. Moreover, I have now tried to shift from `pysam` back to `pyfaidx` for the multiprocessing. 
If this does not solve the issue we will need to memory profile the step; this will require quite a bit of fiddling with the code, especially as I am not able to do the analysis myself on the cluster ...

**Comment by gemygk** [comment]
Hi @lucventurini , the test also failed - with **much** higher memory **>280GB** usage. I think we should revert back to 1a467b4 with fix for **sqlite3.OperationalError: database is locked**
```
sbatch -p ei-cb -c 32 --mem 120G -o out_test_run1_mikado-2.0rc6_dd9e60c_CBG.%j.log -J test_run1_mikado-2.0rc6_dd9e60c_CBG --wrap "source mikado-2.0rc6_dd9e60c_CBG && which mikado && singularity exec /ei/software/cb/mikado/2.0rc6_dd9e60c_CBG/x86_64/mikado-2.0rc6_dd9e60c_CBG.img show_commit_hash && /usr/bin/time -v mikado serialise --seed 10 --procs 32 --json-conf configuration_PickRun2.yaml --output-dir ./test_run1_mikado-2.0rc6_dd9e60c_CBG"
Submitted batch job 25648591
...
...
/ei/software/cb/mikado/2.0rc6_dd9e60c_CBG/x86_64/bin/mikado
dd9e60c9fb04ed30dc8771c86563f6b8504c07d3
slurmstepd: error: Job 25648591 exceeded memory limit (288609460 > 125829120), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 25648591 ON t128n69 CANCELLED AT 2020-02-06T17:23:27 ***
```

Thanks,
Gemy

**Comment by lucventurini** [comment]
Hi @gemygk , OK, thank you. I will revert the changes.
I am now testing on my end using the *H. sapiens* data from the article. Hopefully I will be able to find a solution for this soon.

**Comment by lucventurini** [comment]
Hi @gemygk, I am starting to think that this is not a bug but rather a problem in the SLURM accounting.

I am currently running `mikado serialise` using the *H. sapiens* data, and according to SLURM the process is using either 220GB of RAM (VM) or 133GB (RSS). However, this is **wrong**. Using htop, I can see that the total memory used by `mikado` is actually .... 4GB. I think that SLURM is assigning the memory of the main process to each subprocess and adding them up. 

Of course, I might be wrong. There are two ways we can verify this:

1- please launch `mikado serialise` using the option `--start-type=spawn`, which is normally automatically added by `daijin` (this option should get SLURM to calculate the memory usage correctly).
2- Launch an interactive session, launch `mikado` in the background, and use `top` / `htop` to monitor the memory usage.

Best

**Comment by gemygk** [comment]
Hi @lucventurini 

Please see below my comments post-testing. Sorry for the delay to get back.

> 1- please launch mikado serialise using the option --start-type=spawn, which is normally automatically added by daijin (this option should get SLURM to calculate the memory usage correctly).

I have tested the above option as earlier but the job failed with the same memory issue, as previously stated.

> 2- Launch an interactive session, launch mikado in the background, and use top / htop to monitor the memory usage.

For this, we (@swarbred and me) reduced the input ORF file (limiting to just top ~1500 lines), and we could still see each process using **~4.6GB** of memory (please see the screenshot below). Since this was a reduced input ORF set, we did not hit the SLURM max memory at the ORF loading stage and the ORF's were loaded successfully and started with the blast XML loading. So here, for ORF loading alone, the collective usage (across 30 processes) would have been less than 120GB (requested for the job submission).

![Screenshot 2020-02-12 at 16 30 20](https://user-images.githubusercontent.com/6921000/74355794-39a8bb00-4db5-11ea-8737-5ad9df190010.png)

Once ORF loading was completed, when loading the blast XMLs, the memory usage per process was **~1.5GB** (~45GB collectively across 30 parallel processes), see screenshot below. We can see that the memory consumption per-process is much lower (3x) when loading blast XMLs compared to ORF loading.
![Screenshot 2020-02-12 at 16 30 33](https://user-images.githubusercontent.com/6921000/74355848-4cbb8b00-4db5-11ea-8931-78a0688e9da6.png)

On another note, as you mentioned on the closed issue #177
> Specifically, now mikado serialise can load 954,447 ORFs in just about 3 minutes using 28 parallel processes; at least one minute of this was dedicated to loading the 696,889 transcripts into the "query" table.
Memory was also manageable, with a peak at about 8GBs.

Here, was the peak memory usage you mentioned is per-process i.e., each process using 8GB, or was it collective across 28 parallel processes?


Based on what we see, it feels like we share some data (like mikado_prepared.fasta/GTF, genome.fasta(do we?), etc) with the individual processes during ORF loading causing the high collective memory usage, which does not happen during the stage when we load the blast XMLs.
Can you please check if we are doing something different during the ORF loading stage with parallel processes?


Thanks,
Gemy

```
CMD used:
$ sbatch -w t128n89 -p ei-cb -c 30 --mem 120G -o out_test_run5_mikado-2.0rc6_3f62484_CBG.%j.log -J test_run5_mikado-2.0rc6_3f62484_CBG --wrap "source mikado-2.0rc6_3f62484_CBG && /usr/bin/time -v mikado serialise --seed 10 --procs 30 --json-conf configuration_PickRun2.test_run5.yaml --output-dir ./test_run5_mikado-2.0rc6_3f62484_CBG"
Submitted batch job 25731986
```

**Comment by lucventurini** [comment]
Hi @gemygk , many thanks for checking.
Could you try with d1336e9? In that commit I try to avoid the issue by having `mikado serialise` avoid to load into memory the FAI index of the queries for each subprocess. I thought that was not it, but might as well give it a go. Hopefully this nails it.

**Comment by gemygk** [comment]
Hi @lucventurini 
I will try and let you know.

Can you please comment on what I have asked earlier?
>On another note, as you mentioned on the closed issue #177

>>Specifically, now mikado serialise can load 954,447 ORFs in just about 3 minutes using 28 parallel processes; at least one minute of this was dedicated to loading the 696,889 transcripts into the "query" table.
Memory was also manageable, with a peak at about 8GBs.

>Here, was the peak memory usage you mentioned is per-process i.e., each process using 8GB, or was it collective across 28 parallel processes?

**Comment by lucventurini** [comment]
> Hi @lucventurini
> I will try and let you know.
> 
> Can you please comment on what I have asked earlier?
> 
> > On another note, as you mentioned on the closed issue #177
> 
> > > Specifically, now mikado serialise can load 954,447 ORFs in just about 3 minutes using 28 parallel processes; at least one minute of this was dedicated to loading the 696,889 transcripts into the "query" table.
> > > Memory was also manageable, with a peak at about 8GBs.
> 
> > Here, was the peak memory usage you mentioned is per-process i.e., each process using 8GB, or was it collective across 28 parallel processes?

I think it was collective. I am pretty sure I would have noticed (and the process would have died) otherwise.

**Comment by lucventurini** [comment]
PS if this functions i think I will do another couple of small changes, which do not require testing (mainly code cleanup and compressing data before sending to ancillary processes) before merging into `master`.

**Comment by swarbred** [comment]
@lucventurini so I should use b9ae5b7 to test this

**Comment by lucventurini** [comment]
No, 2c9746b. The other commit is broken.

**Comment by swarbred** [comment]
@lucventurini  @gemygk 

Looks like this has resolved the issue.

*Running with "memory problem" version 3dc2ed9*
set slurm memory limit to 120G

```
       JobID      User    Account    Elapsed  Timelimit     MaxRSS     ReqMem  MaxVMSize      NCPUS ExitCode 
------------ --------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- -------- 
25768073      swarbred       tgac   00:03:44 90-00:00:+                 120Gn                    32      0:0 
25768073.ba+                 tgac   00:03:47            251760096K      120Gn 293114468K         32     0:15 
25768073.ex+                 tgac   00:03:44                 1416K      120Gn    178240K         32      0:0 

```
Job was killed

```
slurmstepd: error: Job 25768073 exceeded memory limit (251760096 > 125829120), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 25768073 ON t128n69 CANCELLED AT 2020-02-15T09:19:52 ***
```

*Running with 2c9746b*
set slurm memory limit to 120G

```
       JobID      User    Account    Elapsed  Timelimit     MaxRSS     ReqMem  MaxVMSize      NCPUS ExitCode 
------------ --------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- -------- 
25763110      swarbred       tgac   04:52:12 7-00:00:00                 120Gn                    32      0:0 
25763110.ba+                 tgac   04:52:12             19417212K      120Gn  61316004K         32      0:0 
25763110.ex+                 tgac   04:52:17                 1452K      120Gn    178208K         32      0:0 

```
Run completed, slurm reporting ~19G memory compared to >250G for the earlier version

@gemygk should probably confirm with his own test but this looks ok to me

**Comment by lucventurini** [comment]
Hi @swarbred , @gemygk 
Excellent, great news. Apparently then that was it - loading of the FAI index into memory for all subprocesses. The only thing that leaves me surprised is that it did not blow up this much on my test machines. 

I will wait for next week before merging into `master` so that @gemygk can run additional tests.

**Comment by lucventurini** [comment]
PS @swarbred, I see that the serialise plus pick took five hours. I would be interested to see where most of the time was spent... Hopefully not in loading the ORFs in the db ...

**Comment by swarbred** [comment]
The 4 hours 52 was for the serialise (-p 32) alone

breakdown is 

~2hrs 30 ORF loading
~2hrs BLAST loading
~8 mins junction loading

the prepare (-p 32) was 55 mins
the pick (-p 32) was 21 mins

So the bulk of our mikado run is in the orf and blast loading

**Comment by lucventurini** [comment]
Mmm. A bit disappointing that it takes so long...the performance is about 135 ORFs per minute per processor.
Still, at least it finishes and with reasonable memory.
