### ISSUE TITLE
Allow stripping of CDS features in pick

### ISSUE THREAD

**Issue by swarbred** [EI-CoreBioinformatics/mikado#271]
@lucventurini another for possible inclusion post 2.0

As we are now using mikado in a more broad context  (i.e. selecting/filtering gene models as well as transcript assemblies) then it would be useful to have more control over what genes are output from mikado as ncRNA features.

There are current pick options relating to the orf loading

```
[pick.orf_loading]
# Parameters related to ORF loading.
# - minimal_secondary_orf_length: Minimum length of a *secondary* ORF to be loaded after the first, in bp. Default: 200 bps
# - minimal_orf_length: Minimum length in bps of an ORF to be loaded, as the primary ORF, onto a transcript. Default: 50 bps
# - strand_specific: Boolean flag. If set to true, monoexonic transcripts will not have their ORF reversed even if they would have an ORF on the opposite strand.
minimal_orf_length = 50
minimal_secondary_orf_length = 200
strand_specific = true

```

These effectively determine what transcripts will have CDS or not i.e. be viewed by pick as ncRNA.

minimal_orf_length = is a crude filter for deciding what to view as ncRNA and it would be dangerous to really alter this much either way.

In the pick requirements we can write an expression to filter models using any of the metrics (including external metrics I believe) but this is all or nothing e.g. we can remove transcripts with a low combined_cds_fraction.coding percentage. 

In some cases you would rather strip the cds but retain the transcript and write an expression specific for this e.g. using a combination of CDS length, coding fraction, even external metrics such as coding potential or blast scores (all things we have in GMC). 

At present  if you use the default scoring you have the oddity that with combined_cds_fraction.coding set in the requirements you would filter out transcripts with a CDS below the cds fraction threshold e.g. below 0.3 but potentially retain smaller transcript fragments from the same loci where the ORF was below the minimal_orf_length i.e. they had no ORF and were viewed as ncRNA.

originally as we completely viewed mikado as a way of selecting coding genes we didn't really care too much but when mikado is used in later steps of the annotation workflow it would be useful to have more control by having a section in the scoring that can control when cds are stripped. The easiest place to do this would seem to be at the stage the requirements are applied.

Again only raise for consideration (and to delay me having to re-grout the shower)

**Comment by lucventurini** [comment]
Hi @swarbred 
OK, this is feasible, but more complex than eg #270. It would require an extra step, before the filtering, but after loading the information from the database.
It will be possible to base this step on a similar machinery to that used for the filtering, but this requires modifying the code in three or four places I would say.

**Comment by lucventurini** [comment]
@swarbred 

Just to be clear on this: what do we need here?

I am thinking that the spec is for a more refined system to accept or reject ORFs from transdecoder / prodigal. I am unclear on what kind of expression we would need here though (fraction of CDS exons over the total?). This might potentially require new metrics (which?). This acceptance / rejection would happen *before* the real picking starts, ie just after loading all the data on.
A good example here might be "if the ncRNA score is present and over a certain threshold, or the ncRNA score is lower than that but the ORF is very short, then reject the CDS".

Am I correct?

**Comment by swarbred** [comment]
Yes the intention was to have more control over which transcripts retain the CDS, currently this is determined by the parameters when running the ORF calling tool or the minimal_orf_length (i.e. solely based on ORF length). 

As an example if we have  a transcript (for arguments sake imagine it intersects no other transcripts) and an orf gets called and meets the minimal_orf_length threshold then this will be output by mikado assuming it meets the requirements section criteria. That orf could be relatively small say 99 bp (the transdecoder default is 100 aa, which excludes many genuine small proteins), if that orf was found in say a  200 bp single exon cDNA then I would view it as more likely to be genuine than say if it fell in the final exon of a 6 exon 2000bp transcript. Currently in both cases it would be included in the final output (ignoring the requirements). In the context of minos if a model has a CDS it has to be regarded as a protein coding gene only those models lacking a CDS get assigned as ncRNA. However I would like to have more control over this as I could imagine using a combination of metrics both internal and external to define when to strip the CDS from a transcript. Even using cds length in conjunction with cds_fraction would allow a user to distinguish between the two transcripts in the above example (other metrics like number of 5' UTR exons, or if the CDS is complete also would be relevant). At the moment you can use the requirements section to filter out transcripts like my 6 exon example but it would be useful to have the ability to retain the transcript but remove the CDS.

In the context of minos we would be able to use additional external metrics that we create i.e. coding potential and blast results of the ORF to determine when to strip the CDS.

In my head I thought it easier to do this after the requirements are applied and before the real picking starts. I think we could come up with a reasonable standard expression based on the internal metrics that would only strip the CDS for those transcripts which have small CDS and very small CDS fraction and perhaps greater than 2 5 UTR exons i would err on the side of caution and only strip those "odd" looking transcripts. And the default is probably not to do this but it would be useful for us to be able to construct an expression for stripping CDS similar to the requirements section. In minos we would also make use of the external metrics.

**Comment by lucventurini** [comment]
@swarbred @gemygk

Please see the latest commit (e993ab8). It should introduce the requested feature as a new field in the scoring file, "cds_requirements", with exactly the same syntax as the other two requirements sections.

This check gets applied in "define_subloci", right before the initial check to remove invalid transcripts.

**Comment by swarbred** [comment]
>This check gets applied in "define_subloci", right before the initial check to remove invalid transcripts.

By this you mean the cds_requirements get applied BEFORE the requirements:?

**Comment by lucventurini** [comment]
> > This check gets applied in "define_subloci", right before the initial check to remove invalid transcripts.
> 
> By this you mean the cds_requirements get applied BEFORE the requirements:?

Yes, exactly. The steps are:

1- Load the transcript data from the database
2- Split chimeric transcripts on the basis of their ORF data
3- Check the CDS, remove the CDS when it does not pass the requirements
4- Remove transcripts that do not meet the minimum requirements
5- start the sublocus etc. definition.

**Comment by swarbred** [comment]
@lucventurini I have tested this on the arabidopsis example region, playing around with a few different expressions. Main thing just running with the default cds requirements (i.e. to do nothing) below, doesn't cause any issues.

cds_requirements:
  expression: [selected_cds_length]
  parameters:
    selected_cds_length: {operator: gt, value: 0}
 
I not that running mikado-issue-271-strip-cds with a scoring file that lacks the cds_requirements: section then the following is sent to stdout/stderr

selected_cds_length
<class 'str'>
selected_cds_length
<class 'str'>

the output was not 100% the same between the run excluding the cds_requirements: and your default cds_requirements (very close to 100% though), so I dont know if running the old scoring with the new mikado version with the cds_requirements changes causes some small issue.

I will need to play around with how best to use this feature so I would suggest we keep the cds_requirements as you have them above for now. 

From me I'm fine with this change and you can merge into master.

**Comment by lucventurini** [comment]
Excellent! I will quickly fix the stdout/stderr messages then merge.
