### ISSUE TITLE
how to remove ncRNA from gff

### ISSUE THREAD

**Issue by lijing28101** [EI-CoreBioinformatics/mikado#273]
Hi, I got the final output from mikado, but I want to remove the ncRNA in the gene model.
Is there any way to do that?

Thanks,
Jing

**Comment by lucventurini** [comment]
Dear @lijing28101 , apologies for the late reply. 

I think that the best option in this sense is a combination of `gffread` and `genometools`, e.g. with the following command line:

```
gffread -F -C ${mikado_output} | gt gff3 -tidy > coding.gff3
gffread -F --nc ${mikado_output} | gt gff3 -tidy > non_coding.gff3  # non-coding models
```

Kind regards

**Comment by lucventurini** [comment]
Closing for now.
