### ISSUE TITLE
Mikado compare fails on lenient

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/mikado#279]
Originally found by @camillaugolini-iit

`mikado compare` fails in lenient mode. Example:

```bash
$ mikado compare --lenient -r Homo_sapiens.GRCh38.99.1.gtf.gz -p file.gff -o 38_gff
[...]
2020-02-26 16:22:19,394 - main_queue - compare.py:878 - ERROR - compare - MainProcess - (29534, 29570)
Traceback (most recent call last):
  File "/home/NHM.AC.UK/lucv/workspace/mikado/Mikado/scales/compare.py", line 876, in compare
    parse_prediction(args, index_name, queue_logger)
  File "/home/NHM.AC.UK/lucv/workspace/mikado/Mikado/scales/compare.py", line 623, in parse_prediction
    done, lastdone = annotator(args, queue_logger, transmit_wrapper, constructor)
  File "/home/NHM.AC.UK/lucv/workspace/mikado/Mikado/scales/compare.py", line 470, in _parse_prediction_gff3
    __found_with_orf=__found_with_orf)
  File "/home/NHM.AC.UK/lucv/workspace/mikado/Mikado/scales/compare.py", line 355, in _transmit_transcript
    transmitter(done, transcript)
  File "/home/NHM.AC.UK/lucv/workspace/mikado/Mikado/scales/compare.py", line 322, in get_best_result
    assigner_instance.get_best(transcript)
  File "/home/NHM.AC.UK/lucv/workspace/mikado/Mikado/scales/assigner.py", line 760, in get_best
    results, best_result = self.__prepare_result(prediction, distances, fuzzymatch=fuzzymatch)
  File "/home/NHM.AC.UK/lucv/workspace/mikado/Mikado/scales/assigner.py", line 541, in __prepare_result
    results, best_result = self.__check_for_fusions(prediction, matches, fuzzymatch=fuzzymatch)
  File "/home/NHM.AC.UK/lucv/workspace/mikado/Mikado/scales/assigner.py", line 417, in __check_for_fusions
    [self.calc_and_store_compare(prediction, tra, fuzzymatch=fuzzymatch) for tra in gene_match],
  File "/home/NHM.AC.UK/lucv/workspace/mikado/Mikado/scales/assigner.py", line 417, in <listcomp>
    [self.calc_and_store_compare(prediction, tra, fuzzymatch=fuzzymatch) for tra in gene_match],
  File "/home/NHM.AC.UK/lucv/workspace/mikado/Mikado/scales/assigner.py", line 814, in calc_and_store_compare
    lenient=self.lenient, fuzzymatch=fuzzymatch)
  File "Mikado/scales/contrast.pyx", line 236, in Mikado.scales.contrast.compare
  File "Mikado/scales/contrast.pyx", line 357, in Mikado.scales.contrast.compare
KeyError: (29534, 29570)
[...]
```

Currently investigating.

**Comment by lucventurini** [comment]
Dear @camillaugolini-iit,

please find a possible fix in 2b161d4.

**Comment by camillaugolini-iit** [comment]
Mi scusi ma da questa mattina sto avendo problemi di accesso al cluster su cui lavoriamo in ufficio, spero di poterle dare al più presto riscontro delle modifiche.

Camilla
________________________________
Da: Luca Venturini <notifications@github.com>
Inviato: giovedì 27 febbraio 2020 17:52:04
A: EI-CoreBioinformatics/mikado
Cc: Camilla Ugolini; Mention
Oggetto: Re: [EI-CoreBioinformatics/mikado] Mikado compare fails on lenient (#279)


Closed #279<https://github.com/EI-CoreBioinformatics/mikado/issues/279>.

**Comment by lucventurini** [comment]
Di nulla, ho comunque fuso i cambiamenti in `master` nel frattempo perché di sicuro risolvono almeno alcuni dei casi.

Quando avrà di nuovo accesso, se potesse installare il ramo `master` e collaudare, le saremmo grati.

Distinti saluti

**Comment by camillaugolini-iit** [comment]
Certo, le farò sapere domani.


Grazie mille

________________________________
Da: Luca Venturini <notifications@github.com>
Inviato: giovedì 27 febbraio 2020 18:29:01
A: EI-CoreBioinformatics/mikado
Cc: Camilla Ugolini; Mention
Oggetto: Re: [EI-CoreBioinformatics/mikado] Mikado compare fails on lenient (#279)


Di nulla, ho comunque fuso i cambiamenti in master nel frattempo perché di sicuro risolvono almeno alcuni dei casi.

Quando avrà di nuovo accesso, se potesse installare il ramo master e collaudare, le saremmo grati.

Distinti saluti

**Comment by camillaugolini-iit** [comment]
Buongiorno,


mikado funziona senza intoppi anche in modalità lenient.

Mi chiedevo se in effetti fosse probabile su una quantità di trascritti pari circa a 30000 che i risultati della modalità stringent e di quella lenient siano esattamente gli stessi.


Grazie mille,


Camilla

________________________________
Da: Camilla Ugolini
Inviato: giovedì 27 febbraio 2020 18:37:17
A: EI-CoreBioinformatics/mikado; EI-CoreBioinformatics/mikado
Cc: Mention
Oggetto: Re: [EI-CoreBioinformatics/mikado] Mikado compare fails on lenient (#279)


Certo, le farò sapere domani.


Grazie mille

________________________________
Da: Luca Venturini <notifications@github.com>
Inviato: giovedì 27 febbraio 2020 18:29:01
A: EI-CoreBioinformatics/mikado
Cc: Camilla Ugolini; Mention
Oggetto: Re: [EI-CoreBioinformatics/mikado] Mikado compare fails on lenient (#279)


Di nulla, ho comunque fuso i cambiamenti in master nel frattempo perché di sicuro risolvono almeno alcuni dei casi.

Quando avrà di nuovo accesso, se potesse installare il ramo master e collaudare, le saremmo grati.

Distinti saluti

**Comment by lucventurini** [comment]
Buongiorno, no, e' effettivamente strano. 

Provo a controllare meglio il codice e le faro' sapere a breve.
Intanto la ringrazio per aver confermato che il baco originale e' stato corretto.

**Comment by lucventurini** [comment]
Buongiorno,
ho ricontrollato e i risultati sono corretti: ovvero, identici nelle statistiche del file `.stats` (dove vengono riportate tutte le statistiche, sia stringenti che rilassate) ma NON nei file `tmap` e `refmap`.
Per la precisione, la differenza e' che in modalita' `lenient` Mikado considera come match completo per un esone **terminale** il solo match del sito di splicing interno (non il match sia del sito di splicing interno che del termine dell'esone). 

Ad es. consideriamo i due trascritti seguenti:
```
Chr1	Mikado	transcript	101	1800	.	+	.	ID=r1.1;Parent=r1
Chr1	Mikado	exon	101	300	.	+	.	ID=r1.1.exon1;Parent=r1.1
Chr1	Mikado	exon	501	800	.	+	.	ID=r1.1.exon2;Parent=r1.1
Chr1	Mikado	exon	1001	1300	.	+	.	ID=r1.1.exon3;Parent=r1.1
Chr1	Mikado	exon	1501	1800	.	+	.	ID=r1.1.exon4;Parent=r1.1
```

e

```
Chr1	Mikado	transcript	201	1700	.	+	.	ID=p1.1;Parent=p1
Chr1	Mikado	exon	201	300	.	+	.	ID=p1.1.exon1;Parent=p1.1
Chr1	Mikado	exon	501	800	.	+	.	ID=p1.1.exon2;Parent=p1.1
Chr1	Mikado	exon	1001	1300	.	+	.	ID=p1.1.exon3;Parent=p1.1
Chr1	Mikado	exon	1501	1700	.	+	.	ID=p1.1.exon4;Parent=p1.1
```

questi trascritti hanno la stessa catena di introni, ma il secondo (`p.1.1`, la nostra "predizione" in questo caso) e' troncato ad entrambi i lati.
Se usiamo `r1.1` come "riferimento" e `p1.1` come "predizione", `mikado compare` in modalita' default da' questi risultati (file `refmap`):
```
ref_id	ccode	tid	gid	nF1	jF1	eF1	ref_gene	best_ccode	best_tid	best_gid	best_nF1	best_jF1	best_eF1	location
r1.1	=	p1.1	p1	90.0	100.0	50.0	r1	=	p1.1	p1	90.0	100.0	50.0	Chr1:101..1800
```

Mentre in modalita' lenient i seguenti:
```
ref_id	ccode	tid	gid	nF1	jF1	eF1	ref_gene	best_ccode	best_tid	best_gid	best_nF1	best_jF1	best_eF1	location
g1.1	=	g1.1	g1	90.0	100.0	100.0	g1	=	g1.1	g1	90.0	100.0	100.0	Chr1:101..1800
```

Come puo' notare la differenza e' nelle statistiche relative agli esoni: in modalita' stringent la concordanza e' solo del 50%, in modalita' lenient e' del 100%.

Spero che questo chiarisca i suoi dubbi.

**Comment by camillaugolini-iit** [comment]
Benissimo grazie molte per tutte le informazioni e il fix del bug.


Cordiali saluti,


Camilla

________________________________
Da: Luca Venturini <notifications@github.com>
Inviato: venerdì 28 febbraio 2020 10:46:03
A: EI-CoreBioinformatics/mikado
Cc: Camilla Ugolini; Mention
Oggetto: Re: [EI-CoreBioinformatics/mikado] Mikado compare fails on lenient (#279)


Buongiorno,
ho ricontrollato e i risultati sono corretti: ovvero, identici nelle statistiche del file .stats (dove vengono riportate tutte le statistiche, sia stringenti che rilassate) ma NON nei file tmap e refmap.
Per la precisione, la differenza e' che in modalita' lenient Mikado considera come match completo per un esone terminale il solo match del sito di splicing interno (non il match sia del sito di splicing interno che del termine dell'esone).

Ad es. consideriamo i due trascritti seguenti:

Chr1    Mikado  transcript      101     1800    .       +       .       ID=r1.1;Parent=r1
Chr1    Mikado  exon    101     300     .       +       .       ID=r1.1.exon1;Parent=r1.1
Chr1    Mikado  exon    501     800     .       +       .       ID=r1.1.exon2;Parent=r1.1
Chr1    Mikado  exon    1001    1300    .       +       .       ID=r1.1.exon3;Parent=r1.1
Chr1    Mikado  exon    1501    1800    .       +       .       ID=r1.1.exon4;Parent=r1.1


e

Chr1    Mikado  transcript      201     1700    .       +       .       ID=p1.1;Parent=p1
Chr1    Mikado  exon    201     300     .       +       .       ID=p1.1.exon1;Parent=p1.1
Chr1    Mikado  exon    501     800     .       +       .       ID=p1.1.exon2;Parent=p1.1
Chr1    Mikado  exon    1001    1300    .       +       .       ID=p1.1.exon3;Parent=p1.1
Chr1    Mikado  exon    1501    1700    .       +       .       ID=p1.1.exon4;Parent=p1.1


questi trascritti hanno la stessa catena di introni, ma il secondo (p.1.1, la nostra "predizione" in questo caso) e' troncato ad entrambi i lati.
Se usiamo r1.1 come "riferimento" e p1.1 come "predizione", mikado compare in modalita' default da' questi risultati (file refmap):

ref_id  ccode   tid     gid     nF1     jF1     eF1     ref_gene        best_ccode      best_tid        best_gid        best_nF1        best_jF1        best_eF1        location
r1.1    =       p1.1    p1      90.0    100.0   50.0    r1      =       p1.1    p1      90.0    100.0   50.0    Chr1:101..1800


Mentre in modalita' lenient i seguenti:

ref_id  ccode   tid     gid     nF1     jF1     eF1     ref_gene        best_ccode      best_tid        best_gid        best_nF1        best_jF1        best_eF1        location
g1.1    =       g1.1    g1      90.0    100.0   100.0   g1      =       g1.1    g1      90.0    100.0   100.0   Chr1:101..1800


Come puo' notare la differenza e' nelle statistiche relative agli esoni: in modalita' stringent la concordanza e' solo del 50%, in modalita' lenient e' del 100%.

Spero che questo chiarisca i suoi dubbi.

**Comment by lucventurini** [comment]
Di nulla. Chiudero' il ticket per il momento.
