### ISSUE TITLE
AMLLoadWarning: calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by jcoludar** [EI-CoreBioinformatics/mikado#288]
Hi guys,

I installed Mikado via pip3 and had all the necessary dependencies installed and working. However, when calling either daijin or mikado the following is returned (below). I would highly appreciate if you can let me know whether it can be fixed and Mikado made executable since the pipeline looks pretty sweet.

Cheers,
Ivan

/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/Mikado/configuration/configurator.py:529: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  scoring = yaml.load(scoring_file)
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/daijin", line 5, in <module>
    from Mikado.daijin import main
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/Mikado/__init__.py", line 34, in <module>
    from . import subprograms
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/Mikado/subprograms/__init__.py", line 17, in <module>
    from . import util
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/Mikado/subprograms/util/__init__.py", line 12, in <module>
    from . import stats
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/Mikado/subprograms/util/stats.py", line 94, in <module>
    class TranscriptComputer(Transcript):
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/Mikado/subprograms/util/stats.py", line 108, in TranscriptComputer
    data_tuple = namedtuple("transcript_data", data_fields, verbose=False)
TypeError: namedtuple() got an unexpected keyword argument 'verbose'

**Comment by lucventurini** [comment]
Hi @jcoludar 

Thank you for contacting us and reporting this bug.
This is a known issue that Mikado 1.2.4 has with Python 3.7 or newer (see [here](https://docs.python.org/3/whatsnew/3.7.html#api-and-feature-removals)).
We are trying to release a new version of Mikado which will have full compatibility with Python 3.7+, but we are not there yet.

In the meantime, and while we decide whether it would make sense to release an official bugfix for 1.2.4, there are three possible options:
- Install Mikado in a Python3.6 environment
- Install Mikado from the `master` branch here, ie a **development** version
- Modify `/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/Mikado/subprograms/util/stats.py` to remove "verbose" from the function call.

Thank you for your understanding.

Kind regards

**Comment by jcoludar** [comment]
thanks a lot!

**Comment by lucventurini** [comment]
This should now be fixed in version 2.0rc2 on both [PyPI](https://pypi.org/project/Mikado/2.0rc2/) and [BioConda](https://anaconda.org/bioconda/mikado). Please repoen if the issue represents itself with the new version!
