### ISSUE TITLE
AttributeError: 'Wildcards' object has no attribute 'sample'

### ISSUE THREAD

**Issue by jcoludar** [EI-CoreBioinformatics/mikado#289]
Hi guys,

I am running Mikado from conda python 3.6, just in case it is important. I have created the daijin config thusly:

daijin configure -o daijin_configure -od master --genome /media/jcoludar/Daten/Ivan/Genomes/GCF_001465965.1_Pdom_r1.2_genomic.fasta --name Polistes_dominula --prot-db /media/jcoludar/Daten/Ivan/Search_DB/toxprot_all_21_02_2020.fasta -al gsnap tophat -as class stringtie trinity --threads 16 -m split -r1 blacklist_paired_unaligned_Podu1.fq -r2  blacklist_paired_unaligned_Podu2.fq --scoring insects.yaml -s Podu3

and when I run daijin assemble like this:

daijin assemble -config daijin_configure -nd

it returns this error:

InputFunctionException in line 699 of /home/jcoludar/anaconda3/envs/python3/lib/python3.6/site-packages/Mikado/daijin/tr.snakefile:
AttributeError: 'Wildcards' object has no attribute 'sample'
Wildcards:
run2=0
alrun=tophat-Podu3-0

Would be absolutely great if you can let me know what I'm doing wrong and how it can be fixed.

Thanks in advance,
Ivan

**Comment by lucventurini** [comment]
Hi @jcoludar ,

I am going to have a look this afternoon. Thank you again for reporting!

**Comment by jcoludar** [comment]
Sorry to bother you again, but after many hours put into trying to run Daijin, I am still experiencing various python-related errors. Is it possible to make a Docker container for the easier use?

**Comment by lucventurini** [comment]
Hi @jcoludar 

It is possible to create a Docker image using the Dockerfiles present in the repository. I confirmed that they function. We also have equivalent recipes for Singularity.

Would that suffice or would you need a release on Dockerhub?

**Comment by jcoludar** [comment]
Hi @lucventurini 
I will try my best, but it would be great if you can put a release on Dockerhub, because that way I can also explain my colleagues how to use it on their machines much easier. On this note, I found this release on the Hub:

https://hub.docker.com/r/cyverseuk/mikado

Can it be used? Or it is not related to this project at all?

Thanks for your prompt reply, I really hope to be able to run pipeline soon )

**Comment by lucventurini** [comment]
> https://hub.docker.com/r/cyverseuk/mikado

This was created a long time ago and I have not verified it in a long while, so I would not trust it.

@swarbred and I are trying to get a proper pre-release done as quickly as possible, so that we can upload it to Conda, PyPI and Dockerhub. **Before we do that, though, we need to finish some coding and test that the results are as expected**. It will take us a little bit of time, but we really would not like to release something on those repositories without the testing being done (even if, admittedly, the current versions are increasingly broken and problematic to use).

I apologise for this, I understand that it might not fit your schedule.

**Comment by jcoludar** [comment]
@lucventurini 

No worries at all. I really like the logic behind the pipeline as I believe the exact issue it aims to address is responsible for all the chimeric, artificially fused genes that plague genomic annotations for non-model species (i.e. most species). The situation is frankly speaking atrocious, so I really wish you success in bringing the pipeline into masses )

I will then make a docker file with the current release and hopefully it works fine. However, would be great if you can give some generous realistic estimate when you expect the new release out. I won't hold you accountable, but I'd like to plan so that when you release it I can re-run the datasets.

**Comment by lucventurini** [comment]
@swarbred over to you regarding timelines.

**Comment by lucventurini** [comment]
This should now be fixed in version 2.0rc2 on both [PyPI](https://pypi.org/project/Mikado/2.0rc2/) and [BioConda](https://anaconda.org/bioconda/mikado). Please repoen if the issue represents itself with the new version!
