### ISSUE TITLE
New defaults / scoring files for Mikado

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/mikado#291]
@swarbred 

A placeholder issue to remind ourselves that you would like to include new scoring files as well as new default values for the configuration.

**Comment by swarbred** [comment]
@lucventurini 
Attached with the changes indicated below, these are based on our experience of runs on mammalian genomes, I've mirrored these in the plant scoring as they should be reasonable selections. In the main these are about allowing longer UTRs are we were finding small UTR fragments represented as separate models (not being removed by the fragmentary checks).

[plant.yaml.txt](https://github.com/EI-CoreBioinformatics/mikado/files/4447139/plant.yaml.txt)
[mammalian.yaml.txt](https://github.com/EI-CoreBioinformatics/mikado/files/4447140/mammalian.yaml.txt)
[configuration.toml.txt](https://github.com/EI-CoreBioinformatics/mikado/files/4447141/configuration.toml.txt)

[**Config**]
max_isoforms = 10
min_cdna_overlap = 0.6
ts_distance = 2000
leniency = "STRINGENT"
intron_range = [60, 10000]
max_regression = 0.2

**Scoring**
combined_cds_fraction.coding: {operator: gt, value: 0.20}

utr_length: {operator: le, value: 3500}
five_utr_length: {operator: le, value: 3500}
three_utr_length: {operator: le, value: 3500}

five_utr_length:
    filter: {operator: le, value: 3500}
    rescaling: target
    value: 400

selected_cds_fraction: {rescaling: target, value: 0.7}

three_utr_length:
    filter: {operator: le, value: 3500}
    rescaling: target
    value: 800

**Comment by swarbred** [comment]
Hi @lucventurini 

Just installed 2.0pcr1 and noticed

leniency = "PERMISSIVE"

rather than STRINGENT

**Comment by lucventurini** [comment]
Hi @swarbred 

My fault, I changed the default values in the configuration files but not in the `configure` etc. programs. Amending now.
