### ISSUE TITLE
question about --max-regression and pad

### ISSUE THREAD

**Issue by lijing28101** [EI-CoreBioinformatics/mikado#301]
Hi, I 'm running the branch of issue270 for two different species.
I compared one case with --max-regression=1 and pad option (case 1), and the other case with --max-regression=0.1 and no pad (case 2).
For arabidopsis, case 1 find a little more (about 1000 more) mRNA than case 2, and the mRNA with start codon and stop codon is about 57% for case 1, 55% for case 2.
But for maize, case 1 fins 1000 less mRNA than case 2, the mRNA with start codon and stop codon is about 67% for case 1, 68% for case 2.
--max-regression set to 1 should find more mRNA according to the manual, because it extend the region to find start codon. But why maize find less mRNA in case 1?
Many predicted CDS dont't have complete structure. Is there a better way to make the predict CDS with start and stop codon?
I know many CDSs from transdecoder are incomplete. Do you have any suggestion for these CDS?

Thanks,
Jing

**Comment by lucventurini** [comment]
Hi @lijing28101 

I think that the issue stems from the way that padding functions, or rather, the end point of the procedure. 

After the padding is finished, there is the possibility of transcripts being redundant. Consider the following scenario:

`______=======--------=========-------==========______`
`______================-------===`
`...............................======--====-===___`

(`=` is CDS, `_` is UTR, `-` is an intron; ignore the dots)
In this mock situation, both the second and the third transcript are potential ASEs of the first.

However, if we use the second as template for the third and viceversa, we end up with two identical transcripts:

`______=======--------=========-------==========______`
`______================-------========--====-===___`
`______================-------========--====-===___`

Mikado will try to remove the redundancy after the padding. This accounts for the lower amount of transcripts. It *could* also account for the lower proportion of complete transcripts.

This is from a very top-level perspective. The best thing would be for you to browse both runs (1 and 2) in IGV or Apollo, and find regions where the output is not what should have been. This would pinpoint those cases where the procedure failed and therefore help us fix it.

I hope this helps.

**Comment by lucventurini** [comment]
Closing for now.
