### ISSUE TITLE
Wrong class code for monoexonic completely contained within a multiexonic transcript

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/mikado#303]
![Wrong_class_code](https://user-images.githubusercontent.com/8897821/78007941-e378e280-7336-11ea-8c39-d5bb8dc449a5.png)

Found by @swarbred 

In this situation, the comparison should give a class code of `c` (with monoexonic prediction and multiexonic reference) or `n` (as reversed).

Instead, the comparison results are `g` and `G`, respectively. This leads `mikado` to accept the multiexonic transcript as a valid ASE.

**Comment by swarbred** [comment]
@lucventurini 

The above example is now correct in the  3f086b5 run
