### ISSUE TITLE
mikado pick error

### ISSUE THREAD

**Issue by javibio-git** [EI-CoreBioinformatics/mikado#306]
Hi Luca, 

I was trying the newest version of mikado and for mikado pick I had the following error:
<img width="1377" alt="Screen Shot 2020-04-30 at 1 23 01 PM" src="https://user-images.githubusercontent.com/14224401/80740733-8c595f80-8ae6-11ea-9cd9-ae399408f7ab.png">

When I go to the log file it seems that mikado pick actually finishes/ran correctly:
<img width="1377" alt="Screen Shot 2020-04-30 at 1 23 36 PM" src="https://user-images.githubusercontent.com/14224401/80740914-ccb8dd80-8ae6-11ea-8aac-b0ac3aed6216.png">

...but when I look at the output gff files, they are not complete; missing annotations for most of the contigs of my genome. 

Do you think it may be because I did not install mikado correctly (I installed the bioconda version)? and/or am I missing any dependency?

Looking forward to hearing back from you. 

Thank you!

**Comment by lucventurini** [comment]
Dear @javbioUMD 

Thanks for reporting the bug. I have not encountered it so far in my runs, basically what is happening here is that at the moment of merging the output, there is a rogue transcript that crashes Mikado. Specifically there seems to be a transcript with more coding exons than it should.

I will have a look at the code to try to understand where the error comes from.

Many thanks

**Comment by lucventurini** [comment]
Closing for now.
