### ISSUE TITLE
excessive run time for mikado prepare

### ISSUE THREAD

**Issue by adamfreedman** [EI-CoreBioinformatics/mikado#308]
I'd used mikado a few times previously on the same data, with reasonable run times (a few hours). I then added a gff3 output from Maker ... and its been 3 days, and still running. All the other inputs previously were gtf files. Given there are 62 input files, does this seem excessive time-wise? Also, another difference with the latest mikado prepare execution, is that the maker input is gff3 ... all other annotations were gtf. Any chance that some aspect of how gff3s are processed is creating the excessive run time (if it seems excessive?)

And a final note ..i've also noticed a bunch of mikado-shelf* files with db, db-wal and db-shm suffixes, which I hadn't seen before, presumably because they are relatively transient during shorter mikado runs.

**Comment by swarbred** [comment]
If you are running with multiple processes this would be excessive, how many transcript level features do you have in your maker file (i.e. distinct features with exons), from memory the Maker output may contain features which you wouldn't want to include e.g. a large number of ab initio predictions. A note of caution, running mikado using the intrinsic metrics is designed mainly for integrating / filtering transcript assemblies rather than gene models. We do use mikado for integrating gene models but we make use of the feature to provide external metrics, to improve the pick process.

**Comment by adamfreedman** [comment]
There are ~ 50k "transcript"-level features in the maker gff3 file, as in, "maker" in column 2 of the gff3, "transcript" in col 3. However, there are a very large number of augustus "match features, ~ 165k. The individual sample-level transcript assemblies contain far fewer features. Furthermore, some runs were submitted to a scheduler, and unintentionally run as single-threaded, while local interactive sessions were running with default of 4 processes. So ... size of maker file x single threaded instances probably the cause of the long run times. 

As far as what you said re: integration of transcripts vs. gene models ... does this mean that mikado may retain > 1 gene models at a single locus (i.e. when there really should be one), and mainly be using mikado pick to extract transcripts from within each locus without integrating across them?

**Comment by lucventurini** [comment]
Dear @adamfreedman 

Apologies for the late reply. The run time seems indeed excessive, and usually the GFF3 input should *not* make a difference.

May I ask which version of mikado you are currently using? We have recently released a version 2 candidate (https://pypi.org/project/Mikado/2.0rc2/ and https://anaconda.org/bioconda/mikado) which might contain the fix for your issue.

**Comment by adamfreedman** [comment]
Hi Luca,

Swarbred did reply to my post back on 5/12. It turns out the maker annotation I had added for integration by Mikado had a lot of ab initio augustus predictions. When those were removed, run time was reasonable ... also, I hadn't realized it was always running as multi-threaded under the hood ... or at least trying to. Previous shorter timed runs were on a local node without any restriction to threads, but the excessively long jobs were run as cluster jobs with one cpu, .... that and the maker addition was a perfect storm. And, I have been using Mikado v2. built not too long ago into a conda environment.

Unrelated to the run time issue, I would love to see more development of Mikado to try to integrate gene model level features, with an eye towards merging gene level annotations that are really only different sets of splice variants originating from the same locus (or different computational inferences of splice variants derived from different inputs that all, collectively, originate from a smaller subset of underlying isoforms). Swarbred indicated that Mikado currently does some, but not much ?, of this integration at the gene level.

For what it's worth, our group is working towards evaluating and deploying best-practice genome annotation pipelines, and I think Mikado has great potential to be the glue that brings together different sources of annotation information. As you no doubt know, there is a rapidly growing need to develop genome annotation pipelines for non-model organisms, and many research groups have approached us as of late seeking guidance. The gene-level integration I refer to above would certainly be a great addition if the Mikado team thinks there is a way forward, and has time to implement it!

Best,
Adam


Adam H. Freedman, PhD
Data Scientist
Faculty of Arts & Sciences Informatics Group
Harvard University
38 Oxford St
Cambridge, MA 02138
phone: +001 310 415 7145
________________________________

**Comment by lucventurini** [comment]
Dear @adamfreedman 

> It turns out the maker annotation I had added for integration by Mikado had a lot of ab initio augustus predictions. When those were removed, run time was reasonable ... also, I hadn't realized it was always running as multi-threaded under the hood ... or at least trying to. Previous shorter timed runs were on a local node without any restriction to threads, but the excessively long jobs were run as cluster jobs with one cpu, .... that and the maker addition was a perfect storm. And, I have been using Mikado v2. built not too long ago into a conda environment.

Yes, `mikado prepare` heavily tries to parallelise to make the process faster. I have tried to optimise the code under the hood, but multiprocessing definitely gives a major boost.
I would be curious about the models that made `mikado prepare` go slow, though; would you by any chance be able to post an example?

> Unrelated to the run time issue, I would love to see more development of Mikado to try to integrate gene model level features, with an eye towards merging gene level annotations that are really only different sets of splice variants originating from the same locus (or different computational inferences of splice variants derived from different inputs that all, collectively, originate from a smaller subset of underlying isoforms). Swarbred indicated that Mikado currently does some, but not much ?, of this integration at the gene level.

We are definitely interested in making Mikado useful in this kind of scenario. May I ask you to elaborate what you envisage as "gene-model level feature integration", please?

Kind regards

Luca Venturini

**Comment by lucventurini** [comment]
Dear @adamfreedman 

I have changed a lot of things under the hood in 0c37624, which should make `prepare` faster and more reliable in the multiprocessing mode.

I will close the issue for now; please reopen if you still have speed issues. 

Many thanks for the original bug report.

**Comment by adamfreedman** [comment]
Hi Luca,

Some time ago, believe I dropped the ball wrt desire for more gene level integration -- I think you were requesting more info re: what I meant, then never got back to you. I will probably follow up re: that in the near future. I am currently deep in a project comparing genome annotation methods, and methods for integrating multiple sources, e.g. mikado.

that said, as you will see shortly, I just submitted an issue re: some odd behavior with seralise that seems to not be properly parsing xml blast format correctly.

Best,
Adam

Adam H. Freedman, PhD
Data Scientist
Faculty of Arts & Sciences Informatics Group
Harvard University
38 Oxford St
Cambridge, MA 02138
phone: +001 310 415 7145

________________________________

**Comment by lucventurini** [comment]
Dear @adamfreedman 

Many thanks for the update. As a general note, I am going to leave my position at the Earlam Institute at the end of this month.

However, my current laboratory (headedby @swarbred) is going to guarantee continuous development and maintenance of the program, with @ljyanesm being tasked with this for the foreseeable future. I will be available for questions but @swarbred and @ljyanesm will be your best port of call going forward.

Of course, we would be happy to have your feedback on how Mikado comes up on your comparison project!

Kind regards,
