### ISSUE TITLE
Various errors while running `mikado configure` 

### ISSUE THREAD

**Issue by LehmannN** [EI-CoreBioinformatics/mikado#310]
Hi, 

I tried to run mikado configure with the command: 
`mikado configure --list list.txt --reference ref.fa --mode permissive -bt UP.fa -t 20 -od mikado_out --strand-specific --scoring mammalian.yaml configuration.yaml`
I observed various errors, so I wondered if this was expected or not. If not, some advices would be welcome. 

1) The `mammalian.yaml` file is in my current directory but I get an error because Mikado will look for it in the installation folder (`/usr/local/lib/python3.6/dist-packages/Mikado/configuration/scoring_files`). I thought of copying the `mammalian.yaml` file in this folder but this would require sudo rights as I'm working on a company server. How could I force Mikado to take the yaml file I have in the current directory ?

I then ran the same command without the scoring file, but still observed some behaviours that I don't think is expected (however these are for information purpose, I can just modify the configuration file - but I was surprised to see this). 
2) The `-t`, `-od` and `--strand-specific` options don't seem to do anything. E.g when I open `configuration.yaml`, I find: `procs: 1`
 `strand_specific: false`
`output_dir: .`

I installed Mikado recently, it's version v1.2.4.
Thanks in advance for your help !

**Comment by lucventurini** [comment]
Dear @LehmannN,

Thank you for reporting this! I think you would be much better served downloading and installing the latest version present on PyPI/Conda (2.0rc2). It is basically finished, it's a release candidate mostly because we want to run a last couple of checks before submitting a paper.

Thank you for your understanding!

**Comment by LehmannN** [comment]
Dear @lucventurini, 

I tried to install the latest version with conda, and got this error: `ModuleNotFoundError: No module named 'Bio._py3k'`. Do you know how this can be fixed ? I installed the whole conda environment with the given environment.yaml file.

Thanks for the help !

**Comment by lucventurini** [comment]
Dear @LehmannN 

Unfortunately this is not an error I have ever encountered - it seems related to how Conda installed the environment, at a hunch. Did you start from a Python2.7 environment by any chance?

**Comment by LehmannN** [comment]
I started from a python 3.7 environment. The conda installation probably did not go through properly. Well, I will try to install it on a smaller server where I have sudo rights (to resolve the problem on the path where Mikado looks for the scoring file), I hope this would work better. I'll let you know!

**Comment by LehmannN** [comment]
Just to let you know, there are still the same issues when installing Mikado through conda, eg: `FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/Mikado/configuration/scoring_files/mammalian.yaml'`.

**Comment by chnyuch** [comment]
> Dear @lucventurini,
> 
> I tried to install the latest version with conda, and got this error: `ModuleNotFoundError: No module named 'Bio._py3k'`. Do you know how this can be fixed ? I installed the whole conda environment with the given environment.yaml file.
> 
> Thanks for the help !

Hi, I encountered the same issue after pip install mikado on my server
I used python 3.7.5, and I did download biopython.
But when I tried to execute mikado, it kept showing that "ModuleNotFoundError: No module named 'Bio._py3k'"
Did you solve this?

**Comment by LehmannN** [comment]
I am working on it, I'll let you know if I find something.

**Comment by LehmannN** [comment]
An update of the errors I get with the installation:
1- installation with `pip3 install mikado`: end with Segmentation fault
2- installation with `conda install -c bioconda mikado` or `conda install -c bioconda/label/cf201901 mikado` :  I get `Found conflicts!` (I sent you the report error @lucventurini ) - python version : 3.7.6.final.0 -  conda version : 4.8.2

**Comment by lucventurini** [comment]
Hi @LehmannN 

Thank you for reporting your problems with the installation! I am investigating now.

Regarding the installation with `pip`, I think that the problem is that environment needs to be configured to have the necessary libraries (not just python) before installing.
This is what I did to install through pip:

```
$ conda create -n test3k python==3.7.5
$ conda install -c anaconda gcc_linux-x64 gxx_linux-x64 zlib
$ pip install numpy scipy cython
$ export CONDA_BUILD=1  # instruct conda to use its own GCC/GXX while in this environment
$ pip install mikado==2.0rc2
$ mikado --version
$ mikado --help
```

On my machine (Windows Linux Subsystem, Ubuntu-based) this procedure allows to install Mikado properly.
On a machine where you are **not** using conda, the third step (installing numpy scipy cython) is essential and should suffice.

Please let me know whether this solves your installation troubles!

**Comment by LehmannN** [comment]
It's working, thanks so much for your help !!
As I am not using conda, I just did:
```
$ pip install numpy scipy cython
$ pip install mikado==2.0rc2
```
Most of the requirements were already satisfied, except `python_rapidjson` and `fastnumbers` so I guess that's were the problem came from.

**Comment by lucventurini** [comment]
> 
> 
> > Dear @lucventurini,
> > I tried to install the latest version with conda, and got this error: `ModuleNotFoundError: No module named 'Bio._py3k'`. Do you know how this can be fixed ? I installed the whole conda environment with the given environment.yaml file.
> > Thanks for the help !
> 
> Hi, I encountered the same issue after pip install mikado on my server
> I used python 3.7.5, and I did download biopython.
> But when I tried to execute mikado, it kept showing that "ModuleNotFoundError: No module named 'Bio._py3k'"
> Did you solve this?

Dear @chnyuch ,

please see above. Hopefully the instructions should help in your case as well.

Kind regards

**Comment by lucventurini** [comment]
> 
> 
> It's working, thanks so much for your help !!
> As I am not using conda, I just did:
> 
> ```
> $ pip install numpy scipy cython
> $ pip install mikado==2.0rc2
> ```
> 
> Most of the requirements were already satisfied, except `python_rapidjson` and `fastnumbers` so I guess that's were the problem came from.

Dear @LehmannN 

Thanks for the feedback! Glad I was able to help.

Please let me know how you get along the new release.

**Comment by chnyuch** [comment]
> It's working, thanks so much for your help !!
> As I am not using conda, I just did:
> 
> ```
> $ pip install numpy scipy cython
> $ pip install mikado==2.0rc2
> ```
> 
> Most of the requirements were already satisfied, except `python_rapidjson` and `fastnumbers` so I guess that's were the problem came from.

Thank you guys! I tried these two commands and it works fine now.
This is really helpful.
