### ISSUE TITLE
KeyError: 'transcript_id' 

### ISSUE THREAD

**Issue by chnych** [EI-CoreBioinformatics/mikado#313]
Hi,

when I am running 

`mikado prepare --json-conf configuration.yaml`

the error occurs: 

> Process AnnotationParser-1:
> Traceback (most recent call last):
>   File "/home/cyc/.local/lib/python3.7/site-packages/Mikado/parsers/GTF.py", line 188, in __set_transcript
>     self._transcript = self.attributes["transcript_id"]
> KeyError: 'transcript_id'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
>     self.run()
>   File "/home/cyc/.local/lib/python3.7/site-packages/Mikado/preparation/annotation_parser.py", line 114, in run
>     strand_specific=strand_specific)
>   File "/home/cyc/.local/lib/python3.7/site-packages/Mikado/preparation/annotation_parser.py", line 592, in load_from_gtf
>     for row in gff_handle:
>   File "/home/cyc/.local/lib/python3.7/site-packages/Mikado/parsers/GTF.py", line 400, in __next__
>     return GtfLine(line)
>   File "/home/cyc/.local/lib/python3.7/site-packages/Mikado/parsers/GTF.py", line 51, in __init__
>     self.__set_parent()
>   File "/home/cyc/.local/lib/python3.7/site-packages/Mikado/parsers/GTF.py", line 213, in __set_parent
>     self.__set_transcript()
>   File "/home/cyc/.local/lib/python3.7/site-packages/Mikado/parsers/GTF.py", line 190, in __set_transcript
>     raise KeyError(self.attributes)
> KeyError: {'Parent': [], 'gene_id': 'scaffold49594_len2841_cov31.0'}
> Mikado prepared has encountered a fatal error. Please check the logs and, if there is a bug,report it to https://github.com/EI-CoreBioinformatics/mikado/issues

I saw similar issue happened before. (https://github.com/EICoreBioinformatics/mikado/issues/243)
But the code in locus.py seems fine.

```
        if self.scores_calculated is True:
            for tid in mapper:
                self.scores[mapper[tid]] = self.scores.pop(tid)
                self._metrics[mapper[tid]] = self._metrics.pop(tid)
        if self.metrics_calculated is True:
            for index in range(len(self.metric_lines_store)):
                self.metric_lines_store[index]["tid"] = mapper[self.metric_lines_store[index]["tid"]]
                self.metric_lines_store[index]["parent"] = self.id
```
My mikado version is "2.0rc2"
Is there any possible problem might cause this issue?

Thank you.

**Comment by cschu** [comment]
Just an idea: we had some similar issue recently, that looks as if there's a line in the input gtf that doesn't have a transcript_id field in column 9 (working with _N. benthamiana_ by chance?)

**Comment by chnych** [comment]
I check the 2 input gtf files, one is generated by class2, the other is generated by stringtie.
Both have gene_id field in column 9. So I am still confused about this issue.
I'm not working with _N. benthamiana_ , I'm working with an avian species.

> scaffold23_len1171_cov16        StringTie       transcript      59      355     1000    .       .       gene_id "stringtie.1"; transcript_id "stringtie.1.1"; cov "3.131313"; FPKM "0.138246"; TPM "0.451859";
> scaffold23_len1171_cov16        StringTie       exon    59      355     1000    .       .       gene_id "stringtie.1"; transcript_id "stringtie.1.1"; exon_number "1"; cov "3.131313";

> scaffold38_len110543_cov24      CLASS   transcript      19366   19807   1000    -       .       gene_id "scaffold38_len110543_cov24.0"; transcript_id "scaffold38_len110543_cov24.0.0"; Abundance "0.020023";
> scaffold38_len110543_cov24      CLASS   exon    19366   19487   1000    -       .       gene_id "scaffold38_len110543_cov24.0"; transcript_id "scaffold38_len110543_cov24.0.0"; exon_number "1"; Abundance "0.020023"

**Comment by swarbred** [comment]
My go to solution when there may be an issue with the input file is to run it through gffread and obtain the -T gtf output and try with this. You could also try using the mikado util convert tool to convert yout gtf to gff3 if that errors then there is likely an issue somewhere in the file.

**Comment by chnych** [comment]
Thanks for the advice.
I used gffread and found the problem is in gtf file generated by CLASS2.

**Comment by lucventurini** [comment]
We are closing this with #365 as we have revised all error messages.
