### ISSUE TITLE
Bioconda Mikado Update?

### ISSUE THREAD

**Issue by cassondranewman** [EI-CoreBioinformatics/mikado#335]
Hello!

Today I installed mikado using `conda install -c bioconda mikado` as directed [here](https://mikado.readthedocs.io/en/latest/Installation.html). 

Running commands threw this error: 
```
/home/cassie.newman/.conda/envs/mikadoenv/lib/python3.6/site-packages/Bio/SubsMat/__init__.py:131: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.
  BiopythonDeprecationWarning,
```

I read through previous github issues and found out that the version of mikado that is installed with `conda install -c bioconda mikado` is v2.0rc2, however to avoid these errors I need a more recent version. Is there anyway the `conda install -c bioconda mikado`  can be updated with the most recent mikado version? 

Thank you!

**Comment by lucventurini** [comment]
Hi @cassondranewman 

You are completely right in your observation. We've been holding up updating mikado for a while due to the fast development cycle, but I think that I will release another version soon, potentially even tomorrow, given that we should have nailed most outstanding issues.

Please stand by, I will let you know when it's ready.

**Comment by cassondranewman** [comment]
Great! I really appreciate it and will be on the look out for the update!

**Comment by lucventurini** [comment]
Hi @cassondranewman ,

We should have updated here as well, but Mikado is now current in Conda and will be updated automatically whenever we release a new version.

Many thanks!
