### ISSUE TITLE
When to add other RNAs

### ISSUE THREAD

**Issue by 14zac2** [EI-CoreBioinformatics/mikado#342]
Hello!

My apologies for all the posts. I am wondering how you recommend dealing with tRNA (& similar non-mRNA) features. Some of my input gtf files contain these features, and yet I believe they get filtered during Mikado, which I believe is optimized for protein-coding genes. Therefore, would you recommend running complete gff output files from Mikado through other tools, such as tRNA-scan to get these features?

Thanks so much for your advice,
Zoe

**Comment by lucventurini** [comment]
Mikado is indeed optimised for mRNAs and, to a lesser extent, ncRNAs (as lower priority). I would certainly encourage you and other users to complement Mikado with other tools that are more geared towards miRNAs, tRNAs, rRNAs, etc. These would most definitely be filtered out by Mikado.

Kind regards

**Comment by 14zac2** [comment]
Wonderful, thanks for the advice!
