### ISSUE TITLE
Add "." for unstranded models in mikado util stats --tab-stats output

### ISSUE THREAD

**Issue by swarbred** [EI-CoreBioinformatics/mikado#378]
Looks like if a model has no strand i.e. "." in the gtf then the tab stats mikado stats output has strand empty i.e. \t\t rather than \t.\t

As I've found out if you sort this with unix sort then the empty column is not counted as a column so your sort ends up sorting on the wrong column. The tab stat output should have unstranded transcripts as strand "."

**Comment by lucventurini** [comment]
Done :-)
