### ISSUE TITLE
missing explaination of mikado.bed in tutorial

### ISSUE THREAD

**Issue by cooketho** [EI-CoreBioinformatics/mikado#385]
Can you please help me understand something about the tutorial? I'm reading here:

https://mikado.readthedocs.io/en/latest/Tutorial/

and I see at the mikado serialize step there is a command which uses a file called mikado.bed:

```
mikado serialise --json-conf configuration.yaml --xml mikado.blast.xml.gz --orfs mikado.bed --blast_targets
```

 but I can't seem to find any step where this file was created, or any previous reference to it in the tutorial. I see a reference to orfs.bed, which the tutorial indicates is from transdecoder. Is this a typo, and the command should have passed orfs.bed to --orfs? Or is this something else? Furthermore, it looks like the text of that command got cut off in the tutorial because --blast_targets needs an argument, but it doesn't have one.

Thanks!

**Comment by lucventurini** [comment]
Dear @cooketho 

Thank you for pointing this out! We are reviewing the documentation these days and we'll make sure to explain this better.

Next Monday I will try to clarify it here as well.

Many thanks again for using our tool and for coming to us with this question, it helps us making Mikado ever better.

Kind regards

Luca Venturini

**Comment by lucventurini** [comment]
Dear @cooketho 

Many apologies for the delay, we were swooped up by our quest to improve the code coverage for the suite.

I have update the documentation (see 8b63828) and we will bring it up live soon.

Kind regards,
