### ISSUE TITLE
Repeat sequences in genome

### ISSUE THREAD

**Issue by wyim-pgl** [EI-CoreBioinformatics/mikado#391]
Dear Luca, @lucventurini 

I have a soft-masked genome that contains repeat sequences. Will Mikado consider such a softmaksed sequence to be a repeat or will it treat soft-masked regions as normal? I noticed that the soft-masked regions aren't considered repeats in the this version.

Thanks

**Comment by lucventurini** [comment]
Dear @wyim-pgl , Mikado will consider the soft masked regions as normal, not as repeats. We currently do not have a method to consider this information within Mikado by eg penalising transcripts that are in full or part within repeats.

I hope this helps.

Kind regards
