### ISSUE TITLE
bug in transcriptchecker.py at line 255

### ISSUE THREAD

**Issue by cooketho** [EI-CoreBioinformatics/mikado#411]
I noticed that when I run mikado, in the resulting file mikado.loci.metrics.tsv the values of the metric "canonical_intron_proportion" was always either 1.0 or 0.0, and often did not agree with manual inspection of the gff. Looking through the code, as far as I can tell these values come from a calculation done in transcriptchecker.py on line 255:

``
self.attributes["canonical_proportion"] = canonical_counter[strand] / len(self.introns)
``
I think this is a bug, and the line should instead be:

``
self.attributes["canonical_proportion"] = canonical_counter[strand] / float(len(self.introns))
``
The problem occurs because in Python when you divide an integer by an integer, it returns an integer, so the bug occurs because any number 0 <= x < 1 will get rounded down to 0, which if you coerce it to a float later, will always become either 1.0 or 0.0, as observed.

**Comment by lucventurini** [comment]
Dear @cooketho ,

Thank you for reporting the bug. I think the reason is different from your hypothesis, though; in Python3 a division between integers will return a float if the result is not exact (so `3/2` is `1` in Python2, but `1.5` in Python3).

We will investigate.

Kind regards

**Comment by swarbred** [comment]
Just to add that with 2.3.0

I can see canonical_intron_proportion set between 0 and 1, so not all transcripts were 0 or 1 exactly

cut -f11 mikado.loci.metrics.tsv |sed 's/^ *//g' |sort -n |uniq -c |sort -nr

 289665 1.0
   1386 0.0
     67 0.75
     59 0.67
     45 0.8
     32 0.83
     27 0.89
     27 0.88
     26 0.86
     25 0.92
     21 0.9
     11 0.93
     10 0.91
      8 0.95
      8 0.94
      5 0.96
      2 0.97

I don't know if this metric (and the other metrics) are recalculated after padding (I think not but Luca can you comment on that).

**Comment by cooketho** [comment]
Ah OK. I think I'm using version 2.0. Maybe it's not an issue with 2.3. I'll upgrade. Thank you!
