### ISSUE TITLE
Testing the installed module UnicodeDecodeError

### ISSUE THREAD

**Issue by bismarck1008** [EI-CoreBioinformatics/mikado#412]
pytest --pyargs Mikado

/test_external_scores.py::ExternalTester::test_invalid_tsv - UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by ljyanesm** [comment]
Dear @bismarck1008,

This is currently fixed in recent issue branches, specifically in commit e807b9a. I will merge and tag a release as soon as possible.

Thank you for reporting this issue, and your patience
Luis
