### ISSUE TITLE
Using mikado to correct MAKER CDS sequences.

### ISSUE THREAD

**Issue by keithforestdecker** [EI-CoreBioinformatics/mikado#414]
Hello,

I have noticed a number of cases for my organism where the MAKER exon structure is correct, but the 5' UTR is incorrect.  This 5' UTR can often be corrected using transdecoder.  

Is there a way to use MIKADO so that, for every gene model, I compare 1) the CDS structure predicted by MAKER and 2) the CDS structure predicted by transdecoder and then use the scoring YAML to choose whether MAKER or transdecoder made the better prediction?

Thanks

**Comment by swarbred** [comment]
Hi @keithforestdecker 

Before i get into what can be done easily with mikado and what would require more work let me make sure I understand what you have and want to achieve.

>the MAKER exon structure is correct, but the 5' UTR is incorrect
>choose whether MAKER or transdecoder made the better prediction

Do you have a gff/gtf with 1) maker models with CDS features called by maker 2) maker models with CDS features called by transdecoder i.e. you you effectively have two alternative sets of gene predictions (sorry I forget exactly what the transdecoder script cdna_alignment_orf_to_genome_orf.pl outputs I assume this is what you have run).

Mikado can be used as a framework to choose between alternative gene models at a locus but the standard metrics https://mikado.readthedocs.io/en/stable/Scoring_files/#metrics alone probably are not the best choice when the input models are not derived directly from transcriptome data. Generally in these cases you want to make that choice on other metrics i.e. evidence support and we have a pipeline built around mikado for that purpose https://github.com/EI-CoreBioinformatics/minos which compares models to protein and transcript alignments + calculates coding potential and uses these external metrics to score the models.

Mikado will allow you to provide external metrics https://mikado.readthedocs.io/en/stable/Scoring_files/#external-metrics that would be generated against the mikado prepare output models or alternatively you can use attributes-metrics that would be included in the input gff/gtfs https://mikado.readthedocs.io/en/stable/Scoring_files/#attributes-metrics

**Comment by keithforestdecker** [comment]
@swarbred 
Thanks for your detailed answer, and for developing/supporting these tools.  I have been using mikado extensively to merge and pick transcripts from multiple annotations runs, incorporating evidence from portcullis/transdecoder etc. as recommended.

I wasn't aware of minos, I will check it out and see if it meets my needs.
