### ISSUE TITLE
Mikado using STAR : limitGenomeGenerateRAM

### ISSUE THREAD

**Issue by NJeanray** [EI-CoreBioinformatics/mikado#416]
Hello,

I'm trying to execute Mikado with STAR, but I get this error : 

> STAR --runThreadN 40 --runMode genomeGenerate --genomeDir /home/NJEANRAY/Daijin/2-alignments/star/index --genomeFastaFiles /home/NJEANRAY/Daijin/0-reference/genome.fa
> 	STAR version: 2.7.9a_2021-06-25   compiled: 2021-08-05T06:34:56+00:00 f90890ab3b7c:/tmp/STAR/source
> Aug 05 12:21:14 ..... started STAR run
> Aug 05 12:21:14 ... starting to generate Genome files
> 
> EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome
> SOLUTION: please specify --limitGenomeGenerateRAM not less than 168632691637 and make that much RAM available 
> 
> Aug 05 12:25:37 ...... FATAL ERROR, exiting

How can I fix this modifying these command lines ? : 

`daijin configure --scheduler SLURM -al {hisat,star,gsnap} -as {stringtie,trinity,cufflinks} --scoring mammalian.yaml -m permissive --sample-sheet /tmpdata/Alternative_Transcripts/samples/sample_sheet.tsv --threads 400 --genome /tmpdata/Genome/Homo_Sapiens/release_104/GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa --queue NJE_patient_24 -o /tmpdata/Alternative_Transcripts/daijin_output/daijin.yaml
`

`daijin assemble --cores 40 /tmpdata/Alternative_Transcripts/daijin_output/daijin.yaml`

Thanks in advance,

Best regards

**Comment by ljyanesm** [comment]
Dear @NJeanray
 
You can add:

```
[aln_index]
star = "--limitGenomeGenerateRAM=<A value for your genome>"
```

To /tmpdata/Alternative_Transcripts/daijin_output/daijin.yaml, which should pass that argument to STAR's index generation.

Kindly,
Luis

**Comment by NJeanray** [comment]
Dear @ljyanesm,

Thanks for your fast answer. Indeed, your suggestion seems to work ! I keep my fingers crossed.

Best regards,
Nathalie

**Comment by ljyanesm** [comment]
Thank you for confirming.

**Comment by NJeanray** [comment]
Your solution was correct. It works perfectly. Thanks !
