### ISSUE TITLE
Allow codon table to be set in mikado prepare

### ISSUE THREAD

**Issue by swarbred** [EI-CoreBioinformatics/mikado#426]
The user selected codon usage table is currently only used in mikado serialise, therefore when CDS features are present in the mikado prepare input these are translated with the standard genetic code (even if an alt has been set) this results in models failing the validation and being removed

Would make sense for the selected codon table to be used in both serialise and prepare.

**Comment by swarbred** [comment]
NOTE This is an issue that will affect reat homology and reat prediction as in both cases models with CDS features are in the GFF input to prepare and there is no way to prevent the check for internal stops (at best strip_faulty_cds: true , will retain the model but then requires ORFs to be recalled)

**Comment by ljyanesm** [comment]
Dear @swarbred,

Can you confirm this is fixed in the main branch? There are 3 commits to this effect on that branch, if so. We can close this ticket once there's a new release.

Best,

**Comment by swarbred** [comment]
@ljyanesm  Yes that's correct, thanks
