### ISSUE TITLE
How to keep CDS information in input gtf files?

### ISSUE THREAD

**Issue by xiekunwhy** [EI-CoreBioinformatics/mikado#427]
Hi,

How to use CDS information in input gtf files? For example, use CDS feature in augustus prediction results.

Best,
Kun

**Comment by swarbred** [comment]
@xiekunwhy You can pass in GTF/GFF files with CDS features and these will be maintained in the output prepare file and used in mikado pick (unless you turn on --strip_cds, there is some validation run as part of prepare that will potentially remove models with non valid CDS e.g. in-frame stops (can be modified with --strip-faulty-cds).

If all your input models have CDS then you dont need to load ORFs in the serialise step.

**Comment by xiekunwhy** [comment]
Ok, thank you for your reply, and I will try it.

**Comment by xiekunwhy** [comment]
If there are CDS informations in gtf/gff files and I also privide ORFs in the serialise step, which information will be used or prefer?

**Comment by xiekunwhy** [comment]
Hi @swarbred ,

I ran mikado like following, but I can not find any CDS feature in mikado_prepared.gtf, what's wrong?

mikado configure --list list.xls --reference zja.scaffold.revision.fa --mode permissive --scoring plant.yaml --copy-scoring plant.yaml --junctions zja.merge.junction.bed -bt proteinDB.fa configuration.yaml
mikado prepare -p 10 --json-conf configuration.yaml
grep -w CDS mikado_prepared.gtf|wc -l
0

All gtf in list.xls file with CDS features.

**Comment by swarbred** [comment]
> If there are CDS informations in gtf/gff files and I also privide ORFs in the serialise step, which information will be used or prefer?

If models are tagged as reference then the CDS info is expected to be in the GFF so this should be used even is orfs are present in serialise. If they are not reference then i'm not certain which would be used, I've always made sure not to provide by both routes i.e. I would run the prepare gtf through gffread and use the option to only out put the non-coding entries and then do the orf calling on this.
