### ISSUE TITLE
Is there a way to update all transcript to complete gene models?

### ISSUE THREAD

**Issue by xiekunwhy** [EI-CoreBioinformatics/mikado#428]
Hi,

I found that there are many incomplete gene models in mikado output gff file, is there a way to update these models to complete gene models?

Best,
Kun

**Comment by sanyalab** [comment]
Hi Kun,

Try TAMA tools. Plus how are you ascertaining the incompleteness of gene models? Using alignment to reference? This works for very very closely related organisms. 

My 2 cents... extract transcripts using gff+genomefasta, gather Iso-Seq genome alignment data (Pacbio/Nanopore), merge using TAMA. Then compare and see what you get.

-Abhijit
