### ISSUE TITLE
Configuration.yaml is empty

### ISSUE THREAD

**Issue by bbista** [EI-CoreBioinformatics/mikado#431]
Hello,
I tested mikado configure on the sample_data but the resulting file Configuration.yaml is empty. I get no error messages.
mikado configure --list list.txt --reference chr5.fas.gz --mode permissive --scoring plant.yaml --copy-scoring plant.yaml --junctions junctions.bed -bt uniprot_sprot_plants.fasta configuration.yaml

I installed  Mikado v2.3.3 from Conda.

Best,
Basanta

**Comment by swarbred** [comment]
@bbista 

I dont see anything obvious can you get the mikado --help have you tried just 

mikado configure --reference YOURFILE.fa configuration.yaml

**Comment by MrbrilliantLL** [comment]
> configuration.yaml

I encountered the same problem. Micado is installed via conda install -c bioconda micado, version 2.2.3.
mikado configure --reference YOURFILE.fa configuration.yaml     
Executing this command will still result in an empty configuration.yaml.

**Comment by ljyanesm** [comment]
Hi all,

I've just had a look and there seems to be an issue with the latest version of one of the dependencies. After pinning it I could generate a correct configuration.

I'll wait for a review on the PR and double check to merge and make a new release to bioconda.
