### ISSUE TITLE
Mikado crashed, cause: unhashable type: 'list'

### ISSUE THREAD

**Issue by dadrasarmin** [EI-CoreBioinformatics/mikado#432]
Hi,

I am using mikado (v2.3.3). I want to change the scoring file according to the information in "6. Adapting Mikado to specific user-cases." I checked some genome annotation files like _[K. nitens](https://ftp.cngb.org/pub/CNSA/data1/CNP0000228/CNS0021447/CNA0002353/scaffold_Chlorokybus_atmophyticus.gff.gz)_, _[M. endlicherianum](https://figshare.com/articles/dataset/Genomes_of_subaerial_Zygnematophyceae_provide_insights_into_land_plant_evolution/9911876/1)_, and _[S. muscicola](https://figshare.com/articles/dataset/Genomes_of_subaerial_Zygnematophyceae_provide_insights_into_land_plant_evolution/9911876/1)_ which are close relatives of the organism I am investigating. There is a problem with the genome annotation files and apparently, mikado cannot handle it. Do you have any suggestions in this regard?

I used:
`mikado util stats 171026_klebsormidium_v1.1.gff 171026_klebsormidium_v1_1.stats`
And I got an empty output file. In the log file I saw this message:
```
2022-05-31 14:47:14,160 - calculator - calculator.py:246 - WARNING - parse_input - MainProcess - No gene found for kfl00001_0010_v1.1, creating a mock one.
Mikado crashed, cause:
unhashable type: 'list'
Traceback (most recent call last):
  File "/usr/users/dadras/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/__main__.py", line 68, in main
    args.func(args)
  File "/usr/users/dadras/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/subprograms/util/stats.py", line 26, in launch
    calculator()
  File "/usr/users/dadras/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/scales/calculator.py", line 348, in __call__
    self.parse_input()
  File "/usr/users/dadras/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/scales/calculator.py", line 314, in parse_input
    orphaned.add(record)
  File "/usr/users/dadras/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 144, in __hash__
    return hash(frozenset(state.items()))
TypeError: unhashable type: 'list'
```

This is the `head` of _K. nitens_ gff file:
```
kfl00001	KFLV1.1	region	1	541865	.	+	.	ID=kfl00001;Name=kfl00001;Note=GenBank:DF236950:Klebsormidium flaccidum DNA%2C scaffold: kfl00001
kfl00001	KFLV1.1	assembly_gap	601	752	.	+	.	ID=KFLV1.1:assembly_gap:kfl00001:601:752;estimated_length=known;gap_type=within scaffold;linkage_evidence=paired-ends
kfl00001	KFLV1.1	assembly_gap	3321	3738	.	+	.	ID=KFLV1.1:assembly_gap:kfl00001:3321:3738;estimated_length=known;gap_type=within scaffold;linkage_evidence=paired-ends
kfl00001	KFLV1.1	assembly_gap	4527	5274	.	+	.	ID=KFLV1.1:assembly_gap:kfl00001:4527:5274;estimated_length=known;gap_type=within scaffold;linkage_evidence=paired-ends
kfl00001	KFLV1.1	mRNA	5705	15555	.	-	.	ID=kfl00001_0010_v1.1;Name=kfl00001_0010_v1.1;Note=prediction v1.10 kfl00001_0010
kfl00001	KFLV1.1	exon	5705	6183	.	-	.	ID=kfl00001_0010_v1.1.exon.1;Alias=kfl00001_0010_v1.1;Name=kfl00001_0010_v1.1
kfl00001	KFLV1.1	exon	7592	7661	.	-	.	ID=kfl00001_0010_v1.1.exon.2;Alias=kfl00001_0010_v1.1;Name=kfl00001_0010_v1.1
kfl00001	KFLV1.1	exon	8320	8805	.	-	.	ID=kfl00001_0010_v1.1.exon.3;Alias=kfl00001_0010_v1.1;Name=kfl00001_0010_v1.1
kfl00001	KFLV1.1	exon	9291	10195	.	-	.	ID=kfl00001_0010_v1.1.exon.4;Alias=kfl00001_0010_v1.1;Name=kfl00001_0010_v1.1
kfl00001	KFLV1.1	exon	11051	11554	.	-	.	ID=kfl00001_0010_v1.1.exon.5;Alias=kfl00001_0010_v1.1;Name=kfl00001_0010_v1.1
```

**Comment by swarbred** [comment]
Hi @dadrasarmin 

Yes the mikado stats has stricter GFF requirements than what some tools generate.

gffread https://github.com/gpertea/gffread tends to be more tolerant so passing the file through this will often generate an appropriate file. I would suggest running through gffread with the -T i.e. gtf output and seeing if that works.

The head you provide above works fine for me even without the "gene" feature so the issue is seemingly elsewhere in the the file.

Again on that section of gff 

mikado util convert -if gff3 -of gtf

will create a gtf file with a mock gene_id

and you can get a valid GFF by then running the GTf file through gffread --keep-genes
